### ISSUE TITLE
Need a rename option for postgresql_db

### ISSUE THREAD

**Issue by asifiqbal** [ansible-collections/community.postgresql#100]
##### ISSUE TYPE
- rename database

##### COMPONENT NAME

- postgresql_db

##### ADDITIONAL INFORMATION

- Need to rename a database

```yaml
  - name: rename a database
    postgresql_db:
        name: currentdb
        state: rename
        target: newdb
```
