### ISSUE TITLE
postgresql_user not idempotent when user privilege set to pg_stat_database:SELECT

### ISSUE THREAD

**Issue by zyitingftnt** [ansible-collections/community.postgresql#122]
##### SUMMARY
postgresql_user module keeps reporting "changed" state for existing postgresql user whose privilege set to **pg_stat_database:SELECT**

However, if I set privilege value to **ALL**, then problem goes away.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
postgresql_user module

##### ANSIBLE VERSION

```
bash-4.4# ansible --version
ansible 2.10.5
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/var/lib/awx/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.6/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.6.8 (default, Aug 24 2020, 17:57:11) [GCC 8.3.1 20191121 (Red Hat 8.3.1-5)]
```

##### COLLECTION VERSION
```
root@server$ ansible-galaxy collection list community.general

# /root/ansible_collections
Collection        Version
----------------- -------
community.general 2.4.0  
```

##### CONFIGURATION
```
root@server$ ansible-config dump --only-changed
COLLECTIONS_PATHS(/root/ansible.cfg) = ['/root/ansible_collections']
DEFAULT_HOST_LIST(/root/ansible.cfg) = ['/root/inventory.ini']
DEFAULT_ROLES_PATH(/root/ansible.cfg) = ['/etc/ansible/roles', '/root/roles']
```

##### OS / ENVIRONMENT
```
CentOS 7
Ansible AWX 16.0.0
```

##### STEPS TO REPRODUCE
```
1. run playbook to create user
2. run the same playbook again
```

##### EXPECTED RESULTS
The task shows OK

##### ACTUAL RESULTS
The task about the user whose priv set to pg_stat_database:SELECT keeps showing "changed" while other users whose priv set to ALL do not have the problem and their states are "OK"

```
master playbook call the task "postgresql_manage_user" from role "postgresql"
---
- name: update postgresql users on standalone or global master
  hosts: "{{ target | default('harbor_all_pgsql') }}"
  gather_facts: true
  remote_user: root
  tasks:
    - include_role:
        name: postgresql
        tasks_from: postgresql_manage_user


task "postgresql_manage_user" playbook as below:
---
- name: update PostgreSQL users
  postgresql_user:
    name: "{{ item.name }}"
    password: "{{ item.password | default(omit) }}"
    encrypted: "{{ item.encrypted | default(omit) }}"
    priv: "{{ item.priv | default(omit) }}"
    role_attr_flags: "{{ item.role_attr_flags | default(omit) }}"
    db: "{{ item.db | default(omit) }}"
    login_host: "{{ item.login_host | default('localhost') }}"
    login_user: "{{ item.login_user | default(postgresql_user) }}"
    login_password: "{{ item.login_password | default(postgresql_pass) }}"
    login_unix_socket: "{{ item.login_unix_socket | default(postgresql_unix_socket_directories) }}"
    port: "{{ item.port | default(omit) }}"
    state: "{{ item.state | default('present') }}"
  with_items: "{{ postgresql_users }}"
  become: true
  become_user: postgres
  vars:
    ansible_ssh_pipelining: true


"postgresql_users" variable contains 3 users as below, the one whose priv set to is the one with non-idempotent problem.
postgresql_users:
  - name: user1
    password: XXXX
    encrypted: yes
    db: postgres
    priv: ALL
    state: present
  - name: user2
    password: XXXX
    encrypted: yes
    db: postgres
    priv: ALL
    state: present
  - name: user3
    password: XXXX
    encrypted: yes
    db: postgres
    priv: pg_stat_database:SELECT   <---------------------------------------------------------
    state: present 
```
