### ISSUE TITLE
pg_hba.conf: add parameter to keep rule-specific comments next to the rule

### ISSUE THREAD

**Issue by betanummeric** [ansible-collections/community.postgresql#134]
##### SUMMARY
My `pg_hba.conf`s often contain comments in the same line as rules, like this:

```
host	db1	user1	2001:db8::1/128	md5	# TICKET-1234
host	db2	user2	192.0.2.2/32	md5	# TICKET-5678
```

Currently, the module `community.postgresql.postgresql_pg_hba` would move those comments to the beginning of the file, which removes the comment-to-rule relation. To optionally preserve that and to optionally add such comments, I propose to introduce two new parameters to the module:

- _keep_comments_at_rules_ (bool, default=false)
  - If true, comments that stand together with a rule in one line are kept behind that line.
  - If false, such comments are moved to the beginning of the file, like all other comments.
- _comment_ (string, optional)
  - A comment that will be placed in the same line behind the rule.

If not set, the behavior of the module remains like before.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
postgresql_pg_hba

##### ADDITIONAL INFORMATION

example use in a playbook:
```yaml
- name: manage pg_hba.conf
  community.postgresql.postgresql_pg_hba:
    address: "{{ address }}"
    contype: host
    create: yes
    databases: "{{ database }}"
    dest: "{{ data_dir }}/pg_hba.conf"
    method: md5
    owner: postgres
    state: present
    users: "{{ username }}"
    keep_comments_at_rules: true
    comment: "this rule is for {{ reason }}"
```

I already started implementing this and will submit a pull request.
