### ISSUE TITLE
postgresql_set failed to import  psycopg2

### ISSUE THREAD

**Issue by RetardedRedhaired** [ansible-collections/community.postgresql#153]
##### SUMMARY
I'm trying to change wal_level to logical and listen_addresses to * using postgresql_set module. But when I run playbook this task fails. Previous task using postgresql_pg_hba module works correctly.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
postgresql_set

##### ANSIBLE VERSION
```
  ansible [core 2.11.5]
  config file = /Users/m.titov/projects/example-postgres-replication/ansible.cfg
  configured module search path = ['/Users/m.titov/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/4.6.0/libexec/lib/python3.9/site-packages/ansible
  ansible collection location = /Users/m.titov/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.9.7 (default, Sep  3 2021, 12:37:55) [Clang 12.0.5 (clang-1205.0.22.9)]
  jinja version = 3.0.1
  libyaml = True
```

##### COLLECTION VERSION
```
# /usr/local/Cellar/ansible/4.6.0/libexec/lib/python3.9/site-packages/ansible_collections
Collection        Version
----------------- -------
community.general 3.7.0

ansible-galaxy collection list community.postgresql

# /usr/local/Cellar/ansible/4.6.0/libexec/lib/python3.9/site-packages/ansible_collections
Collection           Version
-------------------- -------
community.postgresql 1.4.0

# /Users/m.titov/.ansible/collections/ansible_collections
Collection           Version
-------------------- -------
community.postgresql 1.5.0
```

##### CONFIGURATION
```
DEFAULT_HOST_LIST(/Users/m.titov/projects/example-postgres-replication/ansible.cfg) = ['/Users/m.titov/projects/example-postgres-replication/hosts.ini']

ansible.cfg:
[defaults]
inventory = hosts.ini

```

##### OS / ENVIRONMENT
MacOS Big Sur v11.6

##### STEPS TO REPRODUCE
```
  tasks:
    - name: Allowing to accept remote connections in pg_hba file
      community.postgresql.postgresql_pg_hba:
        dest: /var/lib/pgsql/14/data/pg_hba.conf
        contype: host
        users: all
        source: 0.0.0.0/0
        method: md5
        databases: all

    - name: Allowing Postgresql remote TCP/IP connections
      community.postgresql.postgresql_set:
        name: listen_adresses
        value: '*'

    - name: Set wal level to logical
      community.postgresql.postgresql_set:
        name: wal_level
        value: logical

```

##### EXPECTED RESULTS

Expecting to get "ok" status on a task

##### ACTUAL RESULTS

``` 
The full traceback is:
WARNING: The below traceback may *not* be related to the actual failure.
  File "/tmp/ansible_community.postgresql.postgresql_set_payload_BU2tXD/ansible_community.postgresql.postgresql_set_payload.zip/ansible_collections/community/postgresql/plugins/modules/postgresql_set.py", line 169, in <module>
fatal: [centos]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "ca_cert": null,
            "db": null,
            "login_host": "",
            "login_password": "",
            "login_unix_socket": "",
            "login_user": "postgres",
            "name": "listen_adresses",
            "port": 5432,
            "reset": false,
            "session_role": null,
            "ssl_mode": "prefer",
            "trust_input": true,
            "value": "*"
        }
    },
    "msg": "Failed to import the required Python library (psycopg2) on pgtnt-replicator.novalocal's Python /usr/bin/python. Please read the module documentation and install it in the appropriate location. If the required library is installed, but Ansible is using the wrong Python interpreter, please consult the documentation on ansible_python_interpreter"
}

```
