### ISSUE TITLE
It seems to be impossible to create a read only user using postgres_privs

### ISSUE THREAD

**Issue by marcosdiez** [ansible-collections/community.postgresql#175]
I need to create a read only user.

The only way I found out to do it was (check the bottom of this `issue`).

It should be simpler. The syntax does not help, ALL_IN_SCHEMA does not always do what it needs, it seems.

```
  - community.postgresql.postgresql_query:
      login_host: myhost
      login_user: myuser
      login_password: your_bank_password

      db: "{{ item[1] }}"
      query: "grant usage on                schema {{ item[2] }} to  {{ item[0] }}"
    loop: 
      - [ "a_ro_user", "a_db", "a_schema"]

  - community.postgresql.postgresql_query:
      login_host: myhost
      login_user: myuser
      login_password: your_bank_password

      db: "{{ item[1] }}"
      query: "grant select on all tables in schema {{ item[2] }} to  {{ item[0] }}"
    loop: 
      - [ "a_ro_user", "a_db", "a_schema"]

  - community.postgresql.postgresql_query:
      login_host: myhost
      login_user: myuser
      login_password: your_bank_password

      db: "{{ item[1] }}"
      query: "alter default privileges in schema {{ item[2] }} grant select on tables to  {{ item[0] }}"
    loop: 
      - [ "a_ro_user", "a_db", "a_schema"]
````
