### ISSUE TITLE
"database" attribute of "postgresql_schema" being ignored?

### ISSUE THREAD

**Issue by amossc** [ansible-collections/community.postgresql#194]
##### SUMMARY
The `database` attribute is being ignored by `postresql.postgresql_schema`

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
`community.postgresql.postgresql_schema`

##### ANSIBLE VERSION

```paste below
2.10.17
```

##### COLLECTION VERSION

```paste below
1.6.0
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

Ubuntu 20.04.3

##### STEPS TO REPRODUCE

```yaml
- name: Create monitoring schema
  community.postgresql.postgresql_schema:
    name: "monitoring"
    owner: "monitoringuser"
    database: "monitoring"
    login_host: '{{ login_host }}'
    login_user: '{{ db_conn_user }}'
    login_password: '{{ db_conn_pass }}'
```

##### EXPECTED RESULTS

Schema `monitoring` created under the database `monitoring`

##### ACTUAL RESULTS

Schema `monitoring` is created under database `postgres`

```paste below
[localhost] => {
     "changed": false,
     "invocation": {
         "module_args": {
             "ca_cert": null,
             "cascade_drop": false,
             "database": "postgres",
             "login_host": "host.name"
             "login_password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
             "login_unix_socket": "",
             "login_user": "postgres",
             "name": "monitoring",
             "owner": "postgres",
             "port": 5432,
             "schema": "monitoring",
             "session_role": null,
             "ssl_mode": "prefer",
             "state": "present",
             "trust_input": true
         }
     },
     "queries": [],
     "schema": "monitoring"
}
```
