### ISSUE TITLE
community.postgresql.postgresql_ext does not support async

### ISSUE THREAD

**Issue by astrumas** [ansible-collections/community.postgresql#198]
##### SUMMARY
The `community.postgresql.postgresql_ext` module doesn't appear to support `async`.  I have a task that installs many extensions on many databases which by default runs really slow so I thought it would benefit me to use `async`.

This was originally brought up [here](https://stackoverflow.com/questions/71229595/ansible-task-async-with-poll-0-doesnt-move-on-from-task) and was told it would be worth raising an issue here.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
`community.postgresql.postgresql_ext`

##### ANSIBLE VERSION

```
ansible [core 2.11.8] 
  config file = /home/carey/projects/infrastructure_configuration/ansible.cfg
  configured module search path = ['/home/<omitted>/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/<omitted>/.local/lib/python3.8/site-packages/ansible
  ansible collection location = /home/<omitted>/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/<omitted>/.local/bin/ansible
  python version = 3.8.12 (default, Jan 15 2022, 18:39:47) [GCC 7.5.0]
  jinja version = 3.0.3
  libyaml = False
```

##### COLLECTION VERSION

```
Collection           Version
-------------------- -------
community.postgresql 1.6.0
```

##### CONFIGURATION

```
ANSIBLE_FORCE_COLOR = True
ANSIBLE_NOCOWS = True
ANSIBLE_PIPELINING = True
DEFAULT_ACTION_PLUGIN_PATH = ['/usr/share/ansible_plugins/action_plugins']
DEFAULT_ASK_PASS = False
DEFAULT_CALLBACK_PLUGIN_PATH = ['/usr/share/ansible_plugins/callback_plugins']
DEFAULT_CONNECTION_PLUGIN_PATH = ['/usr/share/ansible_plugins/connection_plugins']
DEFAULT_FILTER_PLUGIN_PATH = ['/usr/share/ansible_plugins/filter_plugins']
DEFAULT_FORKS = 20
DEFAULT_GATHERING = implicit
DEFAULT_LOOKUP_PLUGIN_PATH = ['/usr/share/ansible_plugins/lookup_plugins']
DEFAULT_MANAGED_STR = Ansible managed: {file} modified on %Y-%m-%d %H:%M:%S by {uid} on {host}
DEFAULT_POLL_INTERVAL = 15
DEFAULT_REMOTE_PORT = 22
DEFAULT_TIMEOUT = 30
DEFAULT_TRANSPORT = smart
DEFAULT_VARS_PLUGIN_PATH = ['/usr/share/ansible_plugins/vars_plugins']
HOST_KEY_CHECKING = False
RETRY_FILES_ENABLED = False
```

##### OS / ENVIRONMENT

Ubuntu 18.04 (ansible host)
Ubuntu 20.04 (target remote host)

##### STEPS TO REPRODUCE

```yaml
- name: "install postgresql extensions"
  postgresql_ext:
    db: "{{ item[0] }}"
    name: "{{ item[1] }}"
  with_nested:
    - "{{ test_database_list }}"
    - - pageinspect
      - pg_buffercache
      - pg_freespacemap
      - pg_prewarm
      - pg_stat_statements
      - pg_visibility
      - pg_trgm
      - pgrowlocks
      - pgstattuple
  become_user: postgres
  async: 30
  poll: 0
```

##### EXPECTED RESULTS

async works as expected when using poll:0 resulting in the task "firing and forgeting"

##### ACTUAL RESULTS

The task takes longer to run than without async/poll used.  Using async_status module results in `could not find job` error.

Complete task code and result can be found here: https://gist.github.com/astrumas/87e54453d4a1021092e300fd9c6361b9
