### ISSUE TITLE
postgres_privs sets default privilege for types when it should only be doing so for tables

### ISSUE THREAD

**Issue by caseyandgina** [ansible-collections/community.postgresql#207]
##### SUMMARY
When using `postgres_privs` to create a default permission for select access on tables, Ansible is also creating a default permission for usage access on types, which I don't think should be happening.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
community.postgresql.postgresql_privs

##### ANSIBLE VERSION

```paste below
ansible [core 2.12.2]
  config file = None
  configured module search path = ['/Users/cshobe/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /opt/homebrew/Cellar/ansible/5.3.0/libexec/lib/python3.10/site-packages/ansible
  ansible collection location = /Users/cshobe/.ansible/collections:/usr/share/ansible/collections
  executable location = /opt/homebrew/bin/ansible
  python version = 3.10.2 (main, Feb  2 2022, 05:51:25) [Clang 13.0.0 (clang-1300.0.29.3)]
  jinja version = 3.0.3
  libyaml = True
```

##### COLLECTION VERSION

```paste below
Collection           Version
-------------------- -------
community.postgresql 2.1.0  

# /opt/homebrew/Cellar/ansible/5.3.0/libexec/lib/python3.10/site-packages/ansible_collections
Collection           Version
-------------------- -------
community.postgresql 1.6.1  
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

Macos 12.2.1

##### STEPS TO REPRODUCE

Run the following playbook against a database:

```yaml
---

- hosts: 127.0.0.1
  connection: local
  tasks:

  - name: Create user
    postgresql_user:
      login_host: localhost
      port: 5432
      login_user: postgres
      login_password: password
      db: testdb
      name: testuser

  - name: Set default privilege
    postgresql_privs:
      login_host: localhost
      port: 5432
      login_user: postgres
      login_password: password
      database: testdb
      type: default_privs
      schema: public
      privs: SELECT
      objs: TABLES
      roles: testuser
```

##### EXPECTED RESULTS

Here's the same thing I'm trying to accomplish using SQL, and what I would expect to see:

```
testdb=# alter default privileges in schema public grant select on tables to testuser;
ALTER DEFAULT PRIVILEGES
testdb=# \ddp
            Default access privileges
  Owner   | Schema | Type  |  Access privileges  
----------+--------+-------+---------------------
 postgres | public | table | testuser=r/postgres
(1 row)
```

Per the PostgreSQL documentation, the privilege being granted by Ansible on type is usage, which is explained as:

>  For types and domains, allows use of the type or domain in the creation of tables, functions, and other schema objects. (Note that this privilege does not control all “usage” of the type, such as values of the type appearing in queries. It only prevents objects from being created that depend on the type. The main purpose of this privilege is controlling which users can create dependencies on a type, which could prevent the owner from changing the type later.)

Not sure why Ansible is creating this default privilege, but it's not necessary, and if I wanted that, I'd prefer to create it using `type: type` and `privs: USAGE` in the yaml.

##### ACTUAL RESULTS

```
testdb=# \ddp
                        Default access privileges
  Owner   |  Schema  |   Type   |            Access privileges            
----------+----------+----------+-----------------------------------------
 postgres | public   | table    | testuser=r/postgres
 postgres | public   | type     | testuser=U/postgres
(2 rows)
```

**Comment by hunleyd** [comment]
@Andersson007 looking at the code, it seems we should change:
```
def manipulate_privs(self, obj_type, privs, objs, roles, target_roles,
                         state, grant_option, schema_qualifier=None, fail_on_role=True, usage_on_type
s=True):
```
to
```
def manipulate_privs(self, obj_type, privs, objs, roles, target_roles,
                         state, grant_option, schema_qualifier=None, fail_on_role=True, usage_on_type
s=False):
```
yes? AIUI, we would only need to grant usage on types if the user was granting permissions to create future relations using those types.

**Comment by Andersson007** [comment]
@caseyandgina hi, thanks for reporting this!
@hunleyd i think we should 

Looking at the doc, we can see:
```
  usage_on_types:
    description:
    - When adding default privileges, the module always implicitly adds ``USAGE ON TYPES``.
    - To avoid this behavior, set I(usage_on_types) to C(no).
    - Added to save backwards compatibility.
    - Used only when adding default privileges, ignored otherwise.
    type: bool
    default: yes
    version_added: '1.2.0'
```

The questions that come to mind are:
1) Do we really need this option? I've no idea. The description sounds like it's for backwards compatibility only. It would be a breaking change but can we deprecate it and remove in 3.0.0? 
2) If we need it, we should probably change the `default=True` to `default=False` (line 1017):
```
        usage_on_types=dict(type='bool', default=True),
```

What do you folks think?
