### ISSUE TITLE
postgresql_owner change owner on every database

### ISSUE THREAD

**Issue by coopengo-glecomte** [ansible-collections/community.postgresql#240]
##### SUMMARY

The module postgresql_owner update all databases which have the user(s) defined in "reassign_owned_by".

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

postgresql_owner

##### ANSIBLE VERSION

```paste below
ansible [core 2.12.2]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/xxx/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/xxx/.local/lib/python3.8/site-packages/ansible
  ansible collection location = /home/xxx/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/xxx/.local/bin//ansible
  python version = 3.8.10 (default, Mar 15 2022, 12:22:08) [GCC 9.4.0]
  jinja version = 3.0.3
  libyaml = True
```

##### COLLECTION VERSION

```paste below
ansible-galaxy collection list community.postgresql                                                                                                                                                                                     ─╯

# /home/xxx/.local/lib/python3.8/site-packages/ansible_collections
Collection           Version
-------------------- -------
community.postgresql 2.1.3  

# /home/xxx/.ansible/collections/ansible_collections
Collection           Version
-------------------- -------
community.postgresql 2.1.3  

# /usr/local/lib/python3.8/dist-packages/ansible_collections
Collection           Version
-------------------- -------
community.postgresql 2.1.3
```

##### CONFIGURATION

```paste below
ANSIBLE_PIPELINING(/etc/ansible/ansible.cfg) = True
CALLBACKS_ENABLED(/etc/ansible/ansible.cfg) = ['timer', 'profile_roles']
DEFAULT_FORKS(/etc/ansible/ansible.cfg) = 50
DEFAULT_VAULT_PASSWORD_FILE(/etc/ansible/ansible.cfg) = //home/xxx/.ansible/ansible-vault-pass-client
DIFF_ALWAYS(/etc/ansible/ansible.cfg) = True
HOST_KEY_CHECKING(/etc/ansible/ansible.cfg) = False
INTERPRETER_PYTHON(/etc/ansible/ansible.cfg) = /usr/bin/python3
RETRY_FILES_ENABLED(/etc/ansible/ansible.cfg) = False
```

##### OS / ENVIRONMENT

Debian 11

##### STEPS TO REPRODUCE

```yaml
# Variable : 
postgresql_backup_db_to_restore:
  - source: source_db
    target: target_db
    skip_rights: true

- name: Reassign all object in database {{ db_to_restore.target }}
  community.postgresql.postgresql_owner:
    db: "{{ db_to_restore.target }}"
    new_owner: >-
      {% if db_to_restore.owner is defined -%}
        {{ db_to_restore.owner }}
      {%- else -%}
        {{ db_to_restore.source }}
      {%- endif %}
    reassign_owned_by: "{{ postgresql_backup_login.user }}"
    login_user: "{{ postgresql_backup_login.user }}"
    login_password: "{{ postgresql_backup_login.password }}"
    login_host: "{{ postgresql_backup_login.host }}"
  when: not db_to_restore.skip_rights | default(false)
```

##### EXPECTED RESULTS

Only database set in db configuration in task should be updated

postgres : 
```
 test1           | test1    | UTF8     | en_US.UTF-8     | en_US.UTF-8  |
 target_db       | target_db	  | UTF8     | en_US.UTF-8     | en_US.UTF-8  |
 parameter       | admin	  | UTF8     | en_US.UTF-8     | en_US.UTF-8  |
 config          | admin	  | UTF8     | en_US.UTF-8     | en_US.UTF-8  |
 test4           | test4	  | UTF8     | en_US.UTF-8     | en_US.UTF-8  |
```

##### ACTUAL RESULTS

Every database on postgres with the reassign_owned_by have their owner updated

```paste below
<server.name> SSH: EXEC ssh -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o 'ControlPath="/home/xxx/.ansible/cp/2880dfaee1"' backup.coog.io '/bin/sh -c '"'"'sudo -H -S -p "[sudo via ansible, key=hrycfyvoo] password:" -u root /bin/sh -c '"'"'"'"'"'"'"'"'echo BECOME-SUCCESS-hrycfyvoo ; /usr/bin/python3'"'"'"'"'"'"'"'"' && sleep 0'"'"''
Escalation succeeded
<server.name> (0, b'\n{"changed": true, "queries": ["REASSIGN OWNED BY \\"admin\\" TO \\"target_db\\""], "invocation": {"module_args": {"db": "target_db", "new_owner": "target_db", "reassign_owned_by": ["admin"], "login_user": "admin", "login_password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", "login_host": "db.eu-west-3.rds.amazonaws.com", "login_unix_socket": "", "port": 5432, "ssl_mode": "prefer", "fail_on_role": true, "trust_input": true, "ca_cert": null, "obj_name": null, "obj_type": null, "session_role": null}}}\n', b'')
changed: [backup] => {
    "changed": true,
    "invocation": {
        "module_args": {
            "ca_cert": null,
            "db": "target_db",
            "fail_on_role": true,
            "login_host": "db.eu-west-3.rds.amazonaws.com",
            "login_password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "login_unix_socket": "",
            "login_user": "admin",
            "new_owner": "target_db",
            "obj_name": null,
            "obj_type": null,
            "port": 5432,
            "reassign_owned_by": [
                "admin"
            ],
            "session_role": null,
            "ssl_mode": "prefer",
            "trust_input": true
        }
    },
    "queries": [
        "REASSIGN OWNED BY \"admin\" TO \"target_db\""
    ]
}
```

postgres : 
```
 test1           | test1    | UTF8     | en_US.UTF-8     | en_US.UTF-8  |
 target_db       | target_db	  | UTF8     | en_US.UTF-8     | en_US.UTF-8  |
 parameter       | target_db	  | UTF8     | en_US.UTF-8     | en_US.UTF-8  |
 config          | target_db	  | UTF8     | en_US.UTF-8     | en_US.UTF-8  |
 test4           | test4	  | UTF8     | en_US.UTF-8     | en_US.UTF-8  |
```

**Comment by hunleyd** [comment]
thx for the report @coopengo-glecomte ! I'll look into it soon.

**Comment by hunleyd** [comment]
Was able to look closer at this and I don't believe this is a bug @coopengo-glecomte . Looking at the docs for the module:
```
- reassign_owned_by
        The list of role names. The ownership of all the objects
        within the current database, and of all shared objects
        (databases, tablespaces), owned by this role(s) will be
        reassigned to `owner'.
        Pay attention - it reassigns all objects owned by this role(s)
        in the `db'!
        If role(s) exists, always returns changed True.
        Cannot reassign ownership of objects that are required by the
        database system.
        Mutually exclusive with `obj_type'.
        [Default: (null)]
        elements: str
        type: list
```
It seems clear that `reassign_owned_by` will reassign _all shared objects (databases, tablespaces)_ not just the objects in the db you are connected to (see [the PG docs](https://www.postgresql.org/docs/current/role-removal.html) for confirmation of this behavior).

**Comment by Andersson007** [comment]
yep, as @hunleyd wrote, the feature uses the `REASSIGN OWNED BY` postgres' command which doesn't allow to reassign certain objects but all or nothing.

**Comment by hunleyd** [comment]
Let us know if we could make the docs any clearer @coopengo-glecomte otherwise, we'll close this one out in a few days.

**Comment by coopengo-glecomte** [comment]
Thank you for your answer, in this case this is simply a misinterpretation from me due to this sentence in the Ansible documentation which let me understand it's only applied to the current database : 

`Pay attention - it reassigns all objects owned by this role(s) in the db!`

I'll close this issue !

Regards,

**Comment by Andersson007** [comment]
@coopengo-glecomte thanks for pointing this out! We'll fix the documentation, thanks for the contribution!

**Comment by Andersson007** [comment]
I'll open the issue for a while not to forget

**Comment by coopengo-glecomte** [comment]
Thank you @Andersson007 !

**Comment by coopengo-glecomte** [comment]
@Andersson007 to complete the issue, I think you should update examples too : 

```yaml
- name: Reassign all object in database bar owned by bob to alice
  community.postgresql.postgresql_owner:
    db: bar
    new_owner: alice
    reassign_owned_by: bob

- name: Reassign all object in database bar owned by bob and bill to alice
  community.postgresql.postgresql_owner:
    db: bar
    new_owner: alice
    reassign_owned_by:
    - bob
    - bill
```
