### ISSUE TITLE
postgresql_pg_hba module is not idempotent when the task is delegated to another host and there is a loop involved

### ISSUE THREAD

**Issue by jegj** [ansible-collections/community.postgresql#279]
##### SUMMARY
postgresql_pg_hba module is not idempotent when the task is delegated to another host and there is a loop involved

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
postgresql_pg_hba

##### ANSIBLE VERSION

```paste below
ansible [core 2.11.6] 
  config file = /home/jgalarza/playbook/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.8/dist-packages/ansible
  ansible collection location = /home/jgalarza/playbook/collections
  executable location = /usr/local/bin/ansible
  python version = 3.8.10 (default, Mar 15 2022, 12:22:08) [GCC 9.4.0]
  jinja version = 3.1.2
  libyaml = True
```

##### COLLECTION VERSION

```paste below
community.postgresql 2.1.4
```

##### CONFIGURATION

```paste below
COLLECTIONS_PATHS(/home/jgalarza/playbook/ansible.cfg) = ['/home/jgalarza/bidb-rds->
DEFAULT_FORKS(/home/jgalarza/playbook/ansible.cfg) = 20
DEFAULT_REMOTE_USER(/home/jgalarza/playbook/ansible.cfg) = ansible
DEFAULT_ROLES_PATH(/home/jgalarza/playbook/ansible.cfg) = ['/home/jgalarza/bidb-rds>
DEPRECATION_WARNINGS(/home/jgalarza/playbook/ansible.cfg) = False
HOST_KEY_CHECKING(/home/jgalarza/playbook/ansible.cfg) = False
```

##### OS / ENVIRONMENT

Ubuntu 20.04.4 LTS

##### STEPS TO REPRODUCE

```yaml
- name: Whitelist
  community.postgresql.postgresql_pg_hba:
    dest: >-
      /etc/postgresql/{{ item.1.source.PGVERSION }}/{{ item.1.source.PGCLUSTER }}/pg_hba.conf
    contype: "hostssl"
    users: "myuser"
    address: "{{ db_ip }}"
    method: "md5"
    databases: "{{ item.1.source.PGDATABASE }}"
    comment: "WH"
    state: present
  with_subelements:
    - "{{ pgcluster }}"
    - databases
  loop_control:
    label: "{{ item.1.source.PGDATABASE }}"
  delegate_to: "{{ item.1.source.host }}"
  tags: [debug, db]
  register: whitelist_result
```

Inventory 
```json
{
  "ansible_ssh_host": "xxxx",
  "pgcluster": [
    {
      "PGCLUSTER": "main",
      "PGVERSION": 12,
      "PGPORT": 5433,
      "databases": [
        {
          "PGDATABASE": "rep001",
          "source": {
            "PGDATABASE": "src001",
            "host": "src1",
            "PGVERSION": 11,
            "PGCLUSTER": "src1"
          }
        },
        {
          "PGDATABASE": "rep002",
          "source": {
            "PGDATABASE": "src002",
            "host": "src2",
            "PGVERSION": 11,
            "PGCLUSTER": "src2"
          }
        }
      ]
    }
  ]
}
```

##### EXPECTED RESULTS

The task should be idempotent 

##### ACTUAL RESULTS

The task always reports a change. The IP is already whitelisted

```paste below

```
