### ISSUE TITLE
postgresql_membership: remove unnecessary aliases

### ISSUE THREAD

**Issue by Andersson007** [ansible-collections/community.postgresql#296]
##### SUMMARY
I noticed that the `postgresql_membership` module has the following sets of aliases for two parameters.

It is a bad practice as aliases can be introduced for compatibility in case of typos/ unsuitable original choices, etc.

```
 23   groups:
 24     description:
 25     - The list of groups (roles) that need to be granted to or revoked from I(target_roles).
 29     aliases:
 30     - group
 31     - source_role
 32     - source_roles

 33   target_roles:
 34     description:
 35     - The list of target roles (groups will be granted to them).
 39     aliases:
 40     - target_role
 41     - users
 42     - user
```

I suggest choosing one name for each of the options and deprecate (and remove in 3.0.0) the other ones.

I suggest using:
- `source_roles`
- `target_roles`

What do you folks think?

**Comment by hunleyd** [comment]
So `groups` is the list of `roles` that we are GRANTing or REVOKEing and `target_roles` is the recipient of said GRANT/REVOKE. I get where you got 'source' from but I don't think it is "obvious" to end users. So maybe we should `groups -> roles` so it looks like:
```
postgresql_membership:
  roles:
    - hr
    - payroll
   target_roles:
    - bob
    - carol
   state: present
```
I think that's pretty clear what is happening. 

I could even see `target_roles -> targets` so it looks like:
```
postgresql_membership:
  roles:
    - hr
    - payroll
   targets:
    - bob
    - carol
   state: present
```
(I prefer the first example, tbh)

Thoughts @jchancojr @Andersson007 @keithf4 @pgguru ?
