### ISSUE TITLE
postgresql_user: `alter user` statements missing in return value

### ISSUE THREAD

**Issue by betanummeric** [ansible-collections/community.postgresql#307]
### bug
The return value `queries` should contain a "List of executed queries", but when an existing user is alerted the `alter user` statements are not in the return value.

`create user` and `drop user` statements appear as expected in the return value.

### tested versions
community.postgresql: 2.1.5
ansible-playbook: 2.10.8
python: 3.9.2
targeted postgresql: 14

### how to repoduce
```yaml
- hosts: all
  gather_facts: no
  remote_user: postgres
  tasks:
    - name: create user
      community.postgresql.postgresql_user:
        db: postgres
        name: testuser
        password: testpw
        state: present
        login_unix_socket: /tmp
      register: created_user
    - name: debug created_user
      debug:
        msg: "{{ created_user }}"

    - name: alter user
      community.postgresql.postgresql_user:
        db: postgres
        name: testuser
        password: different_password
        state: present
        login_unix_socket: /tmp
      register: altered_user
    - name: debug altered_user
      debug:
        msg: "{{ altered_user }}"

    - name: drop user
      community.postgresql.postgresql_user:
        db: postgres
        name: testuser
        state: absent
        login_unix_socket: /tmp
      register: dropped_user
    - name: debug dropped_user
      debug:
        msg: "{{ dropped_user }}"
```
This outputs:
```
TASK [debug altered_user] ******************************************************************************************************************
task path: /var/go/pwtest/test.yml:26
ok: [my-test-server] => {
    "msg": {
        "changed": true,
        "failed": false,
        "queries": [],
        "user": "testuser"
    }
}
```
But I expected:
```
TASK [debug altered_user] ******************************************************************************************************************
task path: /var/go/pwtest/test.yml:26
ok: [my-test-server] => {
    "msg": {
        "changed": true,
        "failed": false,
        "queries": [
            "ALTER USER \"testuser\" WITH ENCRYPTED PASSWORD %(password)s "
        ],
        "user": "testuser"
    }
}
```
