### ISSUE TITLE
Unable to dynamically use/substitute positional_args to NULLs in postgresql_query

### ISSUE THREAD

**Issue by Iridescens** [ansible-collections/community.postgresql#31]
##### SUMMARY

Unable to dynamically use/substitute positional_args to NULLs in postgresql_query

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

community.general.postgresql_query

##### ANSIBLE VERSION

```paste below
ansible 2.9.14
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/var/lib/awx/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.6/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.6.8 (default, Apr 16 2020, 01:36:27) [GCC 8.3.1 20191121 (Red Hat 8.3.1-5)]
```

##### CONFIGURATION

```paste below
DEFAULT_STDOUT_CALLBACK(/etc/ansible/ansible.cfg) = yaml
HOST_KEY_CHECKING(/etc/ansible/ansible.cfg) = False
```

##### OS / ENVIRONMENT

postgresql11-server-11.9-1PGDG.rhel7.x86_64
NAME="Red Hat Enterprise Linux Server"
VERSION="7.7 (Maipo)"

##### STEPS TO REPRODUCE

Try to dynamically upsert some NULLs into tables

```yaml
community.general.postgresql_query:
        login_host: "{{ awx_request_audit_db_host }}"
        login_user: "{{ awx_request_audit_db_user }}"
        login_password: "{{ awx_request_audit_db_pass }}"
        db: "{{ awx_request_audit_db_name }}"
        query: >
          INSERT INTO request_id_table(request_id)
           VALUES (%s) ON CONFLICT ON CONSTRAINT request_id_table_pk DO NOTHING;
          INSERT INTO requests(request_id,device_hostname,request_type,error_step,config_snapshot,awx_user_name)
           VALUES (%s,%s,%s,%s,%s,%s) ON CONFLICT ON CONSTRAINT requests_pk DO UPDATE
           SET error_step=NULL, config_snapshot=EXCLUDED.config_snapshot, awx_user_name=EXCLUDED.awx_user_name;
          INSERT INTO add_bd_table(request_id,bd_id,bd_vni_id,bd_routedist,bd_subinterface,bd_vlan_id,bd_if_encap)
           VALUES (%s,%s,%s,%s,%s,%s,%s) ON CONFLICT ON CONSTRAINT add_bd_table_pk DO UPDATE
           SET bd_vni_id=EXCLUDED.bd_vni_id,bd_routedist=EXCLUDED.bd_routedist,bd_subinterface=EXCLUDED.bd_subinterface,bd_vlan_id=EXCLUDED.bd_vlan_id,bd_if_encap=EXCLUDED.bd_if_encap;
        positional_args:
          - '{{ request_id }}'
#          - requests
          - '{{ request_id }}'
          - '{{ inventory_hostname }}'
          - '{{ request_type[inventory_hostname] }}'
#          - '{{ error_step[inventory_hostname] }}'
          - NULL
          - '{{ backup_contents_b64.stdout }}'
          - '{{ awx_user_name }}'
#          add_bd_table
          - "{{ request_id }}"
          - "{{ bd_id }}"
          - "{{ bd_vni_id }}"
          - "{{ bd_routedist }}"
          - "{{ bd_subinterface }}"
          - "{{ bd_vlan_id if (bd_vlan_id is defined) else 'NULL' | default('NULL') }}"
          - "{{ bd_if_encap if (bd_if_encap is defined) else 'NULL' | default('NULL') }}"
      delegate_to: localhost
```

##### EXPECTED RESULTS

Being able to provide dynamically assigned NULLs

##### ACTUAL RESULTS

While static NULL (after `#          - '{{ error_step[inventory_hostname] }}'`) does get upserted properly, variables upsert 'NULL' into table or '' (empty string), if used without quotes (just NULL, not 'NULL').
I have searched for the clues in ansible examples and SO with no avail. It is highly likely that I am missing some crucial basic Ansible knowledge, but I just can't find it (or using wrong keywords).

```paste below

```
