### ISSUE TITLE
PGPORT environment variable is ignored

### ISSUE THREAD

**Issue by rgl** [ansible-collections/community.postgresql#311]
##### SUMMARY

The `PGPORT` environment variable is ignored.

Because of that, we have to explicitly set the `port` variable in all the ansible module invocation, which is quite unfortunate.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

postgresql_db

##### ANSIBLE VERSION

```plain
ansible [core 2.13.1]
  config file = /playbooks/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.9/dist-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.9.2 (default, Feb 28 2021, 17:03:44) [GCC 10.2.1 20210110]
  jinja version = 3.1.2
  libyaml = True
```

##### COLLECTION VERSION

```plain
Collection           Version
-------------------- -------
community.postgresql 2.1.5  
```

##### CONFIGURATION

```paste below

```

##### STEPS TO REPRODUCE

1. Start postgres in a non default port (e.g. 1234)
2. Export the `PGPORT=1234` environment variable
3. run the following playbook

```yaml
- hosts: localhost
  connection: local
  tasks:
    - name: Create database
      postgresql_db:
        name: example
        #port: 1234 # this works.
        #port: "{{ lookup('ansible.builtin.env', 'PGPORT') }}" # this also works.
```

##### EXPECTED RESULTS

Expected that exporting the `PGPORT` environment variable would set the used port.

##### ACTUAL RESULTS

```plain
TASK [Create database] *********************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: 	TCP/IP connections on port 5432?
fatal: [localhost]: FAILED! => {"changed": false, "msg": "unable to connect to database: could not connect to server: Connection refused\n\tIs the server running on host \"yb-tservers.yugabytedb\" (10.244.0.18) and accepting\n\tTCP/IP connections on port 5432?\n"}
```

**Comment by hunleyd** [comment]
You will want to set your environment at the play/role/task level as per https://docs.ansible.com/ansible/latest/user_guide/playbooks_environment.html

**Comment by rgl** [comment]
It does not work either:

```yaml
- hosts: localhost
  connection: local
  environment:
    PGPORT: '5433'
  tasks:
    - name: Create database
      postgresql_db:
        name: example
        #port: 1234 # this works.
        #port: "{{ lookup('ansible.builtin.env', 'PGPORT') }}" # this also works.
```

I've added the workaround (commented) `port` definitions that work.

I've added an docker compose drive example that reproduces this is at:

https://github.com/rgl/ansible-init-postgres/blob/main/docker-compose.yml
