### ISSUE TITLE
postgresql_ping crashes parsing the yugabytedb server version

### ISSUE THREAD

**Issue by rgl** [ansible-collections/community.postgresql#315]
##### SUMMARY

`postgresql_ping` crashes parsing the yugabyte (aka yugabytedb) server version:

```
PostgreSQL 11.2-YB-2.15.1.0-b0 on x86_64-pc-linux-gnu, compiled by clang version 13.0.1 (https://github.com/yugabyte/llvm-project.git 191e3a05a55c8671bcc88d7387c04c55a4310500), 64-bit
```

This is similar to https://github.com/ansible-collections/community.postgresql/issues/40. The fix should be similar, but maybe could get the version string with an integer only numbers, for example, using the regex `\d+(\.\d+)+`.

Please let me known if you want me to create a PR.

##### ISSUE TYPE

- Bug Report

##### COMPONENT NAME

postgresql_ping

##### ANSIBLE VERSION

```paste below
ansible core 2.13.1
```

##### COLLECTION VERSION

```paste below
2.1.5
```

##### CONFIGURATION

```paste below

```

##### STEPS TO REPRODUCE

```yaml
                          tasks:
                            - name: Wait for yugabyte to be available
                              community.postgresql.postgresql_ping:
                                db: yugabyte
                                port: "{{ lookup('ansible.builtin.env', 'PGPORT') }}"
                              register: result
                              until: result.get('is_available', False)
                              retries: 6
                              delay: 10
```

##### EXPECTED RESULTS

the ping should have not crashed.

##### ACTUAL RESULTS

```paste below
ansible_community.postgresql.postgresql_ping_payload.zip/ansible_collections/community/postgresql/plugins/modules/postgresql_ping.py\", line 143, in get_pg_version\nValueError: invalid literal for int() with base 10: '2-YB-2'
```
