### ISSUE TITLE
postgresql_query is not able use variable list as postgreSQL Json 

### ISSUE THREAD

**Issue by sivanagireddyb** [ansible-collections/community.postgresql#328]
### Summary

I am not able to use the variable list as postgreSQL Json argument in the psql query

PostgreSQL accept Json in format ["test@gmail.com","test1@gmail.com"]
On manipulating variable list ["test@gmail.com",  "test1@gmail.com"] 

Error:
`
Invalid input syntax for type json\n LINE 1:... Token \"'\" is invalid
`

### Issue Type

Bug Report

### Component Name
postgresql_query

### Ansible Version

```console
$ ansible --version

ansible 2.8.2
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
```

### OS / Environment

CENTOS

### Steps to Reproduce

```yaml (paste below)
vars:
  contacts: ["test@gmail.com", "test2@gmail.com" ]

tasks:
- name: Insert to db
  postgresql_query:
    db: xxx
    login_user: xxx
    login_password: xxx
    query: INSERT INTO test_table (id, contacts) VALUES (%s, %s)
    positional_args:
    - 1
    - '{{ contacts }}'
```

### Expected Results

List variable should be inserted

### Actual Results

```console
Invalid input syntax for type json\n LINE 1:... Token \"'\" is invalid
```
