### ISSUE TITLE
Add support for alter default privileges grant usage on schemas to postgresql_privs

### ISSUE THREAD

**Issue by caseyandgina** [ansible-collections/community.postgresql#332]
##### SUMMARY
I have encountered the same problem described on this closed issue:
https://github.com/ansible/ansible/issues/63273

There was a patch made for it, but for whatever reason that merge request and the issue were closed and the problem still remains.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
community.postgresql.postgresql_privs

##### ANSIBLE VERSION
```paste below
ansible [core 2.12.5]
  config file = /home/ubuntu/worktrees/casey_patroni_fixups/ansible/ansible.cfg
  configured module search path = ['/home/ubuntu/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.8/dist-packages/ansible
  ansible collection location = /home/ubuntu/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.8.10 (default, Jun 22 2022, 20:18:18) [GCC 9.4.0]
  jinja version = 2.10.1
  libyaml = True
```

##### COLLECTION VERSION

```paste below
# /usr/local/lib/python3.8/dist-packages/ansible_collections
Collection           Version
-------------------- -------
community.postgresql 1.6.0  
```

##### CONFIGURATION
```paste below

```

##### OS / ENVIRONMENT
Ubuntu 20.04

##### STEPS TO REPRODUCE
```yaml
- name: Grant datascience usage to all schemas
  community.postgresql.postgresql_privs:
    database: template1
    type: default_privs
    privs: usage
    objs: schemas
    role: datascience
```

##### EXPECTED RESULTS
```sql
alter default privileges
        grant           usage
                on      schemas
                to      "datascience";
```

##### ACTUAL RESULTS
```paste below
Invalid Object set specified: frozenset({'SCHEMAS'})
```
