### ISSUE TITLE
postgresql_privs is not always idempotent

### ISSUE THREAD

**Issue by caseyandgina** [ansible-collections/community.postgresql#343]
It doesn't seem that postgresql_privs is always idempotent as it should be.

The following always makes a change even on repetitive runs:
```
- name: Revoke default public privileges on public schema
  community.postgresql.postgresql_privs:
    database: '{{ database }}'
    type: schema
    objs: public
    privs: create,usage
    state: absent
    roles: PUBLIC
```

Tedious workaround:
```
- name: Determine if usage default privileges have been set
  community.postgresql.postgresql_query:
    db: '{{ database }}'
    query: select ("pg_catalog"."has_schema_privilege" ('public', 'public', 'create') or "pg_catalog"."has_schema_privilege" ('public', 'public', 'usage'))::int "has_schema_privilege"
  register: public_schema_has_default_public_permissions

- name: Revoke default public privileges on public schema
  community.postgresql.postgresql_privs:
    database: '{{ database }}'
    type: schema
    objs: public
    privs: create,usage
    state: absent
    roles: PUBLIC
  when: public_schema_has_default_public_permissions.query_result[0].has_schema_privilege == 1
```

Likewise for this one:

```
- name: Revoke default public permissions on {{ database }} database
  community.postgresql.postgresql_privs:
    database: '{{ database }}'
    type: database
    privs: connect,temporary
    state: absent
    roles: PUBLIC
```

Tedious workaround:
```
- name: Determine if {{ database }} database has default public permissions
  community.postgresql.postgresql_query:
    db: '{{ database }}'
    query: select ("pg_catalog"."has_database_privilege" ('public', '{{ database }}', 'connect') or "pg_catalog"."has_database_privilege" ('public', '{{ database }}', 'temporary'))::int "has_database_privilege"
  register: database_has_default_public_permissions

- name: Revoke default public permissions on {{ database }} database
  community.postgresql.postgresql_privs:
    database: '{{ database }}'
    type: database
    privs: connect,temporary
    state: absent
    roles: PUBLIC
  when: database_has_default_public_permissions.query_result[0].has_database_privilege == 1
```
