### ISSUE TITLE
postgresql_user action fails, but equivalent host action works

### ISSUE THREAD

**Issue by DonBower** [ansible-collections/community.postgresql#345]
##### SUMMARY

While attempting to add a PostgreSQL user, with the task:
```
- name: Create database user
      become: yes
      become_user: postgres
      postgresql_user:
        name: 'xxx'
```
I get the following failure:
```
FAILED! => {"msg": "Failed to set permissions on the temporary files Ansible needs to create when becoming an unprivileged user (rc: 1, err: chmod: invalid mode: ‘A+user:postgres:rx:allow’\nTry 'chmod --help' for more information.\n}). For information on working around this, see https://docs.ansible.com/ansible-core/2.13/user_guide/become.html#risks-of-becoming-an-unprivileged-user"}
```
However, the equivelent host command works just fine:
```
don@pi3:~ $ sudo su postgres -c "createuser xxx"
don@pi3:~ $ 
```

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

postgresql_user

##### ANSIBLE VERSION

```paste below
$ ansible --version
ansible [core 2.13.2]
  config file = /Users/don/Developer/ansible/ansible.cfg
  configured module search path = ['/Users/don/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/don/Library/Python/3.9/lib/python/site-packages/ansible
  ansible collection location = /Users/don/.ansible/collections:/usr/share/ansible/collections
  executable location = /Users/don/Library/Python/3.9/bin/ansible
  python version = 3.9.10 (main, Jan 15 2022, 11:48:04) [Clang 13.0.0 (clang-1300.0.29.3)]
  jinja version = 3.0.3
  libyaml = True
```

##### COLLECTION VERSION

```paste below
ansible-galaxy collection list community.postgresql

# /Users/don/.ansible/collections/ansible_collections
Collection           Version
-------------------- -------
community.postgresql 2.2.0  

# /Users/don/Library/Python/3.9/lib/python/site-packages/ansible_collections
Collection           Version
-------------------- -------
community.postgresql 2.1.5  
```

##### CONFIGURATION

```paste below
ansible-config dump --only-changed
ANSIBLE_NOCOWS(/Users/don/Developer/ansible/ansible.cfg) = True
DEFAULT_HOST_LIST(/Users/don/Developer/ansible/ansible.cfg) = ['/Users/don/Developer/ansible/hosts.>
INTERPRETER_PYTHON(/Users/don/Developer/ansible/ansible.cfg) = auto_silent
```

##### OS / ENVIRONMENT

local: macOS version 12.5.1
remote: 
```
cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

##### STEPS TO REPRODUCE

target machine is a raspberry pi with Postgresql installed (via apt)

```yaml (paste below)
---
- name: Maintain Pi Cluster
  hosts: pi3
  gather_facts: true
  remote_user: don
  become: true

  tasks:
    - name: Create database user
      become: yes
      become_user: postgres
      become_method: su
      postgresql_user:
        name: 'xxx'
```

##### EXPECTED RESULTS

I expected the user xxx to have been created in the postgresql server
I can do other tasks via ansible like find files, update using the apt: service, etc.

##### ACTUAL RESULTS

ansible-playbook fails with error

```paste below
<pi3> Failed to connect to the host via ssh: OpenSSH_8.6p1, LibreSSL 3.3.6
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 21: include /etc/ssh/ssh_config.d/* matched no files
debug1: /etc/ssh/ssh_config line 54: Applying options for *
debug3: expanded UserKnownHostsFile '~/.ssh/known_hosts' -> '/Users/don/.ssh/known_hosts'
debug3: expanded UserKnownHostsFile '~/.ssh/known_hosts2' -> '/Users/don/.ssh/known_hosts2'
debug1: Authenticator provider $SSH_SK_PROVIDER did not resolve; disabling
debug1: auto-mux: Trying existing master
debug2: fd 3 setting O_NONBLOCK
debug2: mux_client_hello_exchange: master version 4
debug3: mux_client_forwards: request forwardings: 0 local, 0 remote
debug3: mux_client_request_session: entering
debug3: mux_client_request_alive: entering
debug3: mux_client_request_alive: done pid = 12781
debug3: mux_client_request_session: session request sent
debug1: mux_client_request_session: master session id: 2
chmod: invalid mode: ‘A+user:postgres:rx:allow’
Try 'chmod --help' for more information.
debug3: mux_client_read_packet: read header failed: Broken pipe
debug2: Received exit status from master 1
<pi3> ESTABLISH SSH CONNECTION FOR USER: don
<pi3> SSH: EXEC ssh -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="don"' -o ConnectTimeout=10 -o 'ControlPath="/Users/don/.ansible/cp/ee3dc26a1c"' pi3 '/bin/sh -c '"'"'rm -f -r /var/tmp/ansible-tmp-1662835310.29893-12797-234267342779192/ > /dev/null 2>&1 && sleep 0'"'"''
<pi3> (0, b'', b"OpenSSH_8.6p1, LibreSSL 3.3.6\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug1: /etc/ssh/ssh_config line 21: include /etc/ssh/ssh_config.d/* matched no files\r\ndebug1: /etc/ssh/ssh_config line 54: Applying options for *\r\ndebug3: expanded UserKnownHostsFile '~/.ssh/known_hosts' -> '/Users/don/.ssh/known_hosts'\r\ndebug3: expanded UserKnownHostsFile '~/.ssh/known_hosts2' -> '/Users/don/.ssh/known_hosts2'\r\ndebug1: Authenticator provider $SSH_SK_PROVIDER did not resolve; disabling\r\ndebug1: auto-mux: Trying existing master\r\ndebug2: fd 3 setting O_NONBLOCK\r\ndebug2: mux_client_hello_exchange: master version 4\r\ndebug3: mux_client_forwards: request forwardings: 0 local, 0 remote\r\ndebug3: mux_client_request_session: entering\r\ndebug3: mux_client_request_alive: entering\r\ndebug3: mux_client_request_alive: done pid = 12781\r\ndebug3: mux_client_request_session: session request sent\r\ndebug1: mux_client_request_session: master session id: 2\r\ndebug3: mux_client_read_packet: read header failed: Broken pipe\r\ndebug2: Received exit status from master 0\r\n")
fatal: [pi3]: FAILED! => {
    "msg": "Failed to set permissions on the temporary files Ansible needs to create when becoming an unprivileged user (rc: 1, err: OpenSSH_8.6p1, LibreSSL 3.3.6\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug1: /etc/ssh/ssh_config line 21: include /etc/ssh/ssh_config.d/* matched no files\r\ndebug1: /etc/ssh/ssh_config line 54: Applying options for *\r\ndebug3: expanded UserKnownHostsFile '~/.ssh/known_hosts' -> '/Users/don/.ssh/known_hosts'\r\ndebug3: expanded UserKnownHostsFile '~/.ssh/known_hosts2' -> '/Users/don/.ssh/known_hosts2'\r\ndebug1: Authenticator provider $SSH_SK_PROVIDER did not resolve; disabling\r\ndebug1: auto-mux: Trying existing master\r\ndebug2: fd 3 setting O_NONBLOCK\r\ndebug2: mux_client_hello_exchange: master version 4\r\ndebug3: mux_client_forwards: request forwardings: 0 local, 0 remote\r\ndebug3: mux_client_request_session: entering\r\ndebug3: mux_client_request_alive: entering\r\ndebug3: mux_client_request_alive: done pid = 12781\r\ndebug3: mux_client_request_session: session request sent\r\ndebug1: mux_client_request_session: master session id: 2\r\nchmod: invalid mode: ‘A+user:postgres:rx:allow’\nTry 'chmod --help' for more information.\ndebug3: mux_client_read_packet: read header failed: Broken pipe\r\ndebug2: Received exit status from master 1\r\n}). For information on working around this, see https://docs.ansible.com/ansible-core/2.13/user_guide/become.html#risks-of-becoming-an-unprivileged-user"
}

PLAY RECAP *********************************************************************
pi3              : ok=1    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
```

**Comment by DonBower** [comment]
I have the same issue on an ubuntu 20.04, so pretty sure this may be the way I am using this.

**Comment by hunleyd** [comment]
This isn't an issue w/ the postgresql_user module, it's telling you that $HOME/.ansible/tmp was created with the wrong permissions. If you delete it, that directory should be automatically recreated with the proper permissions.

**Comment by DonBower** [comment]
I deleted the `~/.ansible/tmp` directory, same result.
That directory had the same permissions as the `~/.ansible` did, 700.
I opened up both directories to 777, and that did not work either.
Given that these are brand new machines, I would have to say if Ansible is not configured properly, then there is a problem with the docs.
but at this point, I think their man be something wrong with the module after all.

**Comment by DonBower** [comment]
Finally got this to work from a fresh OS install.
Three things were necessary:

1. SUDO must be allowed to switch to the `postgres` user without password required
2. `psycopg2-binary` module must be installed from root, with umask = 0022. 
3. use of `community.postgresql.*` requires the use of ansible_ssh_pipelining, because the ~/.ansible/tmp dir does not permit use by the user `postgres` 

I offer the following playbook to demonstrate:
```yaml
---
- name: Maintain Pi Cluster
  hosts: pi3
  gather_facts: true
  remote_user: don
  become: true

  tasks:
    - name: Ping the Servers
      ansible.builtin.ping:

    - name: Get WHOAMI user
      become:      false
      local_action: command whoami
      register:    whoami
    - debug: msg="{{ whoami.stdout }}"

    - name: Allow SUDO without PW
      ansible.builtin.lineinfile:
        path: /etc/sudoers.d/010_pi-nopasswd
        create: true
        mode: u=r,g=r,o=
        state: present
        line: "{{whoami.stdout}} ALL=(ALL) NOPASSWD: ALL"

    - name: Upgrade installed APT Packages
      ansible.builtin.apt:
        upgrade: yes
        update_cache: yes

    - name: Install APT Packages
      ansible.builtin.apt:
        pkg:
        - net-tools
        - netcat
        - dnsutils
        - python-is-python3
        - python3-pip
        - wget
        - jq
        - curl
        - apt-transport-https
        - ca-certificates
        state: present

    - name: Install psycopg2-binary module
      become: true
      ansible.builtin.pip:
        name:
        - psycopg2-binary
        umask: "0022"

    - name: Install Postgress SQL Server
      apt:
        name:
        - postgresql
        state: present

    - name: Create user
      become: true
      become_user: postgres
      community.postgresql.postgresql_user:
        name: "{{ whoami.stdout }}"
      vars:
        ansible_ssh_pipelining: true
```
