### ISSUE TITLE
module development: postgresql_funcs

### ISSUE THREAD

**Issue by stefanvdm-em** [ansible-collections/community.postgresql#348]
##### SUMMARY
Create, alter or drop PostgreSQL functions.

##### ISSUE TYPE
- Module development

##### COMPONENT NAME
postgresql_funcs

##### ADDITIONAL INFORMATION
Example usage:
```yaml
- name: Sum of integers function
  community.postgresql.postgresql_funcs:
      function: sum_of_integers
      language: plpgsql
      return_type: integer
      arguments:
          - "a ingeter"
          - "b integer"
      source: "BEGIN RETURN a+b; END;"
```

##### PROPOSED ANSIBLE ARGUMENTS
Considering the most basic and minimal usage of [CREATE FUNCTION](https://www.postgresql.org/docs/current/sql-createfunction.html)
```sql
CREATE FUNCTION return_some_integer()
    RETURNS integer
    LANGUAGE 'plpgsql'
    AS
    $$
    BEGIN
        RETURN 1;
    END
    $$;
```
we can see that we will always need:
- a name for our function,
- the return type,
- the language of the function, and
- some source code for the definition of the function.

From my limited personal use of PostgreSQL functions, I have used the following attributes the most:
- behaviour (IMMUTABLE, STABLE, VOLATILE),
- null argument calling (CALLED ON NULL INPUT, RETURNS NULL ON NULL INPUT, STRICT), and
- security (SECURITY INVOKER, SECURITY DEFINER).

My suggestion would be to include the above-mentioned arguments initially and then expand to include all remaining options later.

##### APPROACH
Since PostgreSQL functions are named objects, similar to tables, I think it best to base the development of **postgresql_funcs** on **postgresql_table**.
