### ISSUE TITLE
Not possible to define composite primary key with postgresql_table

### ISSUE THREAD

**Issue by mmauksch** [ansible-collections/community.postgresql#359]
##### SUMMARY
The postgresql_table module currently doesn't have the functionality to create a composite primary key spanning multiple columns. This would be required for some table designs though

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
postgresql_table

##### ADDITIONAL INFORMATION
Why is it useful? Composite primary keys are an integral part of a clean database design. Well known usecase: m:n relationship tables.
Functionality can be emulated by using not null colums and creating a composite unique index. Relational database design required every table to have a primary key though.

Example usage:
```yaml
- name: create user mapping table
  community.postgresql.postgresql_table:
    owner: exampleuser
    name: rel_user_group
    columns: 
      - "user_id integer references user.id"
      - "group_id integer references group.id"
    primary_key_columns:
      - user_id
      - group_id
    db: exampledatabase
```

**Comment by Andersson007** [comment]
@mmauksch hello, thanks for reporting this!
I'd like to ask your general opinion on the module?

The context is that, imo, it's not designed well in general providing only partly idempotance (i'm the author and i was green at that time and we wrote `postgresql_query` later).
`postgresql_table` is just a kind of query constructor. Yep, it can change something (like table's owner iirc) but it can't, say, re-arrange a column order (we can implement it but the data will be lost...)
Maybe we should deprecate `postgresql_table`, as well as `postgresql_idx`, and use the `postgresql_query` instead?

Ideas from other contributors/users are welcome (@hunleyd, @betanummeric)

**Comment by mmauksch** [comment]
General opinion on the module? It's useful. But without the ability to do composite primary keys it's missing some crucial functionality in my opinion.
In my specific case that lead me to writing the ticket? I learned that the service I wanted to deploy with ansible needs a init setup to be run anyways which provisions the tables. So my use for the module in that case is moot now. Still a useful feature though if the module will not be buried.
For my one of my work related playbook the composite primary key is a thing again^^ so need to stay on "run psql file" for now.
What I liked about the modul was the whole: the table is already in the right state: i'm green let's move on. My "run an SQL script" always reports as changed. Might be a problem with my SQL file though which I need to look at another time.

**Comment by jericson** [comment]
I'm not sure if this is a change, a hidden feature or just a lucky coincidence, but I found you can pass a primary key constraint via the column definition:

```
    - name: Create completions (A) table
      community.postgresql.postgresql_table:
        name: c2023a
        columns:
          - UNITID numeric
          - CIPCODE text
          - MAJORNUM numeric
          - AWLEVEL numeric
...
          - primary key (UNITID, CIPCODE, MAJORNUM, AWLEVEL)
```

And sure enough, it has a composite primary key:

```
ndexes:
    "c2023a_pkey" PRIMARY KEY, btree (unitid, cipcode, majornum, awlevel)
```

H/T: https://stackoverflow.com/questions/72766109/ansible-postgresql-table-how-to-create-a-foreign-key-constraint
