### ISSUE TITLE
Add support for partitions to postgresql_table

### ISSUE THREAD

**Issue by SiL3x** [ansible-collections/community.postgresql#372]
##### SUMMARY

For larger databases it would be a nice improvement to be able to manage partitioned tables and partitions using the postgresql_table module. 
Managing in this context includes (but is not limited to):
 - Creating partitioned tables 
 - Attach & detach partitions

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

postgresql_table

##### ADDITIONAL INFORMATION

- This feature would be used while creating tables (see below for two ideas).  
- The ability to create and manage partitioned tables is important to work with big tables.

```yaml
- name: Create test_table with several columns and partitioned by date range
  community.postgresql.postgresql_table:
    name: test_table
    columns:
    - id bigserial primary key
    - num bigint
    - date date
    partition: range (date)
```
```yaml
- name: Create test_table_2022 with several columns and attach it to test_table
  community.postgresql.postgresql_table:
    name: test_table
    columns:
    - id bigserial primary key
    - num bigint
    - date date
    partition: of test_table for values from ('2022-01-01') to ('2023-01-01')
```
