### ISSUE TITLE
postgresql_privs fails with type=default_privs, privs=ALL, objs=ALL_DEFAULT

### ISSUE THREAD

**Issue by vonschultz** [ansible-collections/community.postgresql#373]
##### SUMMARY

With Ansible 6.6.0 `postgresql_privs` fails when running with type=default_privs, privs=ALL, objs=ALL_DEFAULT. The issue appears to have been introduced in commit eed4e1f4641acc6181647e7d18bd550261a282d5 which added `SCHEMAS` to the `VALID_DEFAULT_OBJS` variable and thereby to the `ALL_DEFAULT` objs, despite `SCHEMAS` not being supported with `privs=ALL`.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

`postgresql_privs`

##### ANSIBLE VERSION

```paste below
$ ansible  --version
ansible [core 2.13.6]
  config file = /home/von/.ansible.cfg
  configured module search path = ['/home/von/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/von/src/embedl/ci/provisioning/.tox/ansible/lib/python3.8/site-packages/ansible
  ansible collection location = /home/von/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/von/src/embedl/ci/provisioning/.tox/ansible/bin/ansible
  python version = 3.8.10 (default, Jun 22 2022, 20:18:18) [GCC 9.4.0]
  jinja version = 3.1.2
  libyaml = True
```

```
$ pip show ansible
Name: ansible
Version: 6.6.0
Summary: Radically simple IT automation
Home-page: https://ansible.com/
Author: Ansible, Inc.
Author-email: info@ansible.com
License: GPLv3+
Location: /home/von/src/embedl/ci/provisioning/.tox/ansible/lib/python3.8/site-packages
Requires: ansible-core
Required-by: 
```

Note that the problem is not exhibited in `ansible` version 6.5.0.

##### COLLECTION VERSION

```paste below
$ ansible-galaxy collection list community.postgresql

# /home/von/src/embedl/ci/provisioning/.tox/ansible/lib/python3.8/site-packages/ansible_collections
Collection           Version
-------------------- -------
community.postgresql 2.3.0  
```

##### CONFIGURATION

`ansible-config dump --only-changed` reports no changes

##### OS / ENVIRONMENT

Ubuntu 20.04, Postgresql 13.

##### STEPS TO REPRODUCE

This is the exact task that's failing for me with `ansible` version 6.6.0, but which works fine for `ansible` version 6.5.0:
```yaml
- name: "ALTER DEFAULT PRIVILEGES FOR ROLE {{ username }}"
  postgresql_privs:
    db: "{{ item }}"
    objs: ALL_DEFAULT
    privs: ALL
    type: default_privs
    role: "{{ item }}"
    target_roles: "{{ username }}"
    ca_cert: "{{ ca_cert }}"
    ssl_mode: verify-full
    login_host: "{{ postgres_public_hostname }}"
    login_password: "{{ postgres_admin_password }}"
  loop: "{{ user_accounts[username]['postgres_roles'] }}"
```

I think you'll find that this example in the documentation exhibits the same problem:
```yaml
# Objs must be set, ALL_DEFAULT to TABLES/SEQUENCES/TYPES/FUNCTIONS
# ALL_DEFAULT works only with privs=ALL
# For specific
- name: ALTER DEFAULT PRIVILEGES ON DATABASE library TO librarian
  community.postgresql.postgresql_privs:
    db: library
    objs: ALL_DEFAULT
    privs: ALL
    type: default_privs
    role: librarian
    grant_option: true
```

##### EXPECTED RESULTS

Task runs without error on latest version of `ansible` (given that it runs without error on `ansible` 6.5.0).

##### ACTUAL RESULTS

```paste below
failed: [localhost] (item=embedl) => {
    "ansible_loop_var": "item",
    "changed": false,
    "invocation": {
        "module_args": {
            "ca_cert": "/etc/ssl/certs/ISRG_Root_X1.pem",
            "connect_params": {},
            "database": "embedl",
            "db": "embedl",
            "fail_on_role": true,
            "grant_option": null,
            "host": "postgres.embedl.dev",
            "login": "postgres",
            "login_host": "postgres.embedl.dev",
            "login_password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "login_unix_socket": "",
            "login_user": "postgres",
            "objs": "ALL_DEFAULT",
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "port": 5432,
            "privs": "ALL",
            "role": "embedl",
            "roles": "embedl",
            "schema": null,
            "session_role": null,
            "ssl_mode": "verify-full",
            "state": "present",
            "target_roles": "daniel",
            "trust_input": true,
            "type": "default_privs",
            "unix_socket": "",
            "usage_on_types": true
        }
    },
    "item": "embedl",
    "msg": "Invalid priv specified. Valid object for priv: frozenset({'SEQUENCES', 'TYPES', 'TABLES', 'FUNCTIONS'}). Objects: frozenset({'TYPES', 'FUNCTIONS', 'SEQUENCES', 'TABLES', 'SCHEMAS'})"
}
```
