### ISSUE TITLE
The 'postgresql_privs' module cannot grant access to database by another role

### ISSUE THREAD

**Issue by drybjed** [ansible-collections/community.postgresql#38]
##### SUMMARY

The `postgresql_privs` role is broken when trying to grant access to a PostgreSQL database owned by one role, to a different PostgreSQL role.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

postgresql_privs

##### ANSIBLE VERSION

```paste below
ansible 2.10.4
  config file = None
  configured module search path = ['/home/drybjed/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/drybjed/.local/lib/python3.7/site-packages/ansible
  executable location = /home/drybjed/.local/bin/ansible
  python version = 3.7.3 (default, Dec 20 2019, 18:57:59) [GCC 8.3.0]
```

##### CONFIGURATION

```paste below
Empty output
```

##### OS / ENVIRONMENT

OS: Debian Buster
Database: PostgreSQL 11

##### STEPS TO REPRODUCE

The idea is to create a PostgreSQL "database role" which is an owner of the database itself and cannot be logged in directly. Then, an "application role" is granted access to the "database role", and this allows the application role to access the database without the ability to remove the database itself, or perform other admin-level tasks on it, for security reasons.

```yaml
---

- hosts: 'localhost'
  become: True

  tasks:

    - name: Create database role
      postgresql_user:
        name: "gitlabhq_production"
        role_attr_flags: "NOLOGIN"
        state: present
      become: True
      become_user: 'postgres'

    - name: Create database
      postgresql_db:
        name: "gitlabhq_production"
        owner: 'gitlabhq_production'
        state: present
      become: True
      become_user: 'postgres'

    - name: Create application role
      postgresql_user:
        name: "gitlab"
        state: present
      become: True
      become_user: 'postgres'

    - name: "Grant access to database role by application role"
      postgresql_privs:
        roles: "gitlab"
        type: "group"
        objs: "gitlabhq_production"
        database: "gitlabhq_production"
      become: True
      become_user: 'postgres'
```

##### EXPECTED RESULTS

The `postgres_privs` module should grant access to the `gitlabhq_production` PostgreSQL role by the `gitlab` PostgreSQL role.

##### ACTUAL RESULTS

```paste below
PLAY [localhost] ********************************************************************************************************************************************

TASK [Gathering Facts] *********************************************************************************************************************************
ok: [localhost]

TASK [Create database role] ****************************************************************************************************************************
changed: [localhost]

TASK [Create database] *********************************************************************************************************************************
changed: [localhost]

TASK [Create application role] *************************************************************************************************************************
changed: [localhost]

TASK [Grant access from app role to database role] *****************************************************************************************************
fatal: [localhost]: FAILED! => changed=false 
  msg: |-
    zero-length delimited identifier at or near """"
    LINE 1: GRANT ""gitlabhq_production"" TO "gitlab";
                   ^

```
Output of the failed task with -vvvv debugging enabled:
```
TASK [Grant access from app role to database role] *****************************************************************************************************
task path: /home/drybjed/src/projects/lxc.tycho.drybjed.net/playbooks/test-postgres.yml:31                                                             
The full traceback is:
  File "/tmp/ansible_postgresql_privs_payload_s8jzrx80/ansible_postgresql_privs_payload.zip/ansible_collections/community/general/plugins/modules/postgresql_privs.py", line 1120, in main
  File "/tmp/ansible_postgresql_privs_payload_s8jzrx80/ansible_postgresql_privs_payload.zip/ansible_collections/community/general/plugins/modules/postgresql_privs.py", line 802, in manipulate_privs
fatal: [code]: FAILED! => changed=false 
  invocation:
    module_args:
      ca_cert: null
      database: gitlabhq_production
      fail_on_role: true
      grant_option: null
      host: ''
      login: postgres
      login_host: ''
      login_password: ''
      login_unix_socket: ''
      login_user: postgres
      objs: gitlabhq_production
      password: ''
      port: 5432
      privs: null
      roles: gitlab
      schema: null
      session_role: null
      ssl_mode: prefer
      state: present
      target_roles: null
      trust_input: true
      type: group
      unix_socket: ''
      usage_on_types: true
  msg: |-
    zero-length delimited identifier at or near """"
    LINE 1: GRANT ""gitlabhq_production"" TO "gitlab";
                   ^
```

**Comment by tcraxs** [comment]
!component =postgresql_privs

**Comment by tcraxs** [comment]
bot_status

**Comment by tcraxs** [comment]
The problematic thing is the quoting. I checked this on a local PostgreSQL 13.1:
```
postgres=# GRANT ""gitlabhq_production"" TO "gitlab";
ERROR:  zero-length delimited identifier at or near """"
LINE 1: GRANT ""gitlabhq_production"" TO "gitlab";
              ^
postgres=# GRANT "gitlabhq_production" TO "gitlab";
GRANT ROLE
```

**Comment by tcraxs** [comment]
So it sums up to a forced quoting of an already quoted string in [code line 803](https://github.com/ansible-collections/community.postgresql/blob/main/plugins/modules/postgresql_privs.py#L803).

**Comment by Andersson007** [comment]
@drybjed thanks for reporting this!
@tcraxsthanks for the investigation, would you like to fix this?

**Comment by Andersson007** [comment]
I had a quick look: if we remove the double quotes, the tests in the part related to names with dots will fail.
I stripped the quotes from a role like this:
```
 802                 else:
 803                     for_whom.append('"%s"' % r.strip('"'))
```
and the current tests pass.
Maybe there are other options how to fix this more gracefully. We definitely should cover the module better

**Comment by Andersson007** [comment]
@drybjed btw, while it's not fixed, you could use `postgresql_user` module with `groups` parameter or `postgresql_membership` module, e.g.:
```
    - name: Create application role
      postgresql_user:
        name: "gitlab"
        groups: "gitlabhq_production"
        state: present
      become: True
      become_user: 'postgres'
```
