### ISSUE TITLE
`db` option on `postgresql_user` don't work

### ISSUE THREAD

**Issue by mm3906078** [ansible-collections/community.postgresql#397]
##### SUMMARY
Hi everyone,
I have a problem with the user module. When I create a `test` DB and I create a user like `john` and I want to give the user access to the `test` DB, I can not do it by `db` option on the user module.

PS: I read the code and I think this argument won't work without `priv`. Do I understand right?

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
[postgresql_user.py](https://github.com/ansible-collections/community.postgresql/blob/main/plugins/modules/postgresql_user.py)

##### STEPS TO REPRODUCE
```
      - name: Create database.
        community.postgresql.postgresql_db:
          name: "test"
          state: present

      - name: Create user.
        community.postgresql.postgresql_user:
          db: test
          name: "john"
          password: "john@john"
          expires: infinity
          state: present
```

##### EXPECTED RESULTS
```
postgres=# \l
                                  List of databases
   Name    |  Owner   | Encoding |   Collate   |    Ctype    |   Access privileges
-----------+----------+----------+-------------+-------------+-----------------------
 postgres  | postgres | UTF8     | en_US.UTF-8 | en_US.UTF-8 |
 template0 | postgres | UTF8     | en_US.UTF-8 | en_US.UTF-8 | =c/postgres          +
           |          |          |             |             | postgres=CTc/postgres
 template1 | postgres | UTF8     | en_US.UTF-8 | en_US.UTF-8 | =c/postgres          +
           |          |          |             |             | postgres=CTc/postgres
 test      | postgres | UTF8     | en_US.UTF-8 | en_US.UTF-8 | john=CTc/post

```

##### ACTUAL RESULTS
```
postgres=# \l
                                  List of databases
   Name    |  Owner   | Encoding |   Collate   |    Ctype    |   Access privileges
-----------+----------+----------+-------------+-------------+-----------------------
 postgres  | postgres | UTF8     | en_US.UTF-8 | en_US.UTF-8 |
 template0 | postgres | UTF8     | en_US.UTF-8 | en_US.UTF-8 | =c/postgres          +
           |          |          |             |             | postgres=CTc/postgres
 template1 | postgres | UTF8     | en_US.UTF-8 | en_US.UTF-8 | =c/postgres          +
           |          |          |             |             | postgres=CTc/postgres
 test      | postgres | UTF8     | en_US.UTF-8 | en_US.UTF-8 |
```

**Comment by hunleyd** [comment]
hello @mm3906078 thanks for the report!
can you try:
```
- name: Create user.
        community.postgresql.postgresql_user:
          db: test
          name: "john"
          password: "john@john"
          expires: infinity
          state: present
          priv: "CONNECT"
```
and see if that behaved as expected?
