### ISSUE TITLE
update_password: on_create

### ISSUE THREAD

**Issue by nbari** [ansible-collections/community.postgresql#416]
##### SUMMARY
add `update_password`:  with options like `always`, `on_create` like the [mysql_user](https://docs.ansible.com/ansible/latest/collections/community/mysql/mysql_user_module.html#parameter-update_password) to prevent changing the password if already exists

##### COMPONENT NAME

postgres_user

##### ADDITIONAL INFORMATION

```yaml
- name: Create user
  postgresql_user:
    name: test
    password: secret
    update_password: on_create
```
