### ISSUE TITLE
ldapbindpasswd in options which includes  '#' creates faulty pg_hba lines

### ISSUE THREAD

**Issue by stelb** [ansible-collections/community.postgresql#420]
##### SUMMARY
ldapbindpasswd in options which includes  '#' creates faulty pg_hba lines
While a hashmark in a password might be ugly I cannot change this

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
postgresql_pg_hba

##### ANSIBLE VERSION

```paste below

ansible [core 2.11.12]
  config file = None
  configured module search path = ['/home/USER/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/USER/.local/lib/python3.6/site-packages/ansible
  ansible collection location = /home/USER/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/USER/.local/bin/ansible
  python version = 3.6.8 (default, Aug 13 2020, 07:46:32) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
  jinja version = 3.0.1
  libyaml = True

```

##### COLLECTION VERSION

```paste below
Collection           Version
-------------------- -------
community.postgresql 2.3.2
```

##### CONFIGURATION

```paste below

```

##### STEPS TO REPRODUCE

```yaml
---
- hosts: localhost
  tasks:
    - name: line 1
      community.postgresql.postgresql_pg_hba:
        dest: pg_hba.conf
        create: yes
        users: bug
        databases: bug
        source: 66.66.66.66/32
        contype: hostssl
        method: ldap
        options: ldapbindpasswd ="#BROKEN"
        keep_comments_at_rules: true
        comment: messed up
    - name: line 2 breaks line 1
      community.postgresql.postgresql_pg_hba:
        dest: pg_hba.conf
        create: yes
        users: bug2
        databases: bug
        source: 66.66.66.66/32
        contype: hostssl
        method: ldap
        options: ldapbindpasswd ="#BROKEN"
        keep_comments_at_rules: true
```

##### EXPECTED RESULTS

file pg_hba should be:
```
hostssl bug     bug     66.66.66.66/32  ldap    ldapbindpasswd ="#BROKEN"        #messed up
hostssl bug     bug2    66.66.66.66/32  ldap    ldapbindpasswd ="#BROKEN"
```

##### ACTUAL RESULTS

pg_hba.conf generated is:
```
hostssl bug     bug     66.66.66.66/32  ldap    ldapbindpasswd ="    #BROKEN"        #messed up
hostssl bug     bug2    66.66.66.66/32  ldap    ldapbindpasswd ="#BROKEN"
```

```paste below
PLAY [localhost] *****************************************************************************************************************************************************************************************************************************************************************************

TASK [Gathering Facts] ***********************************************************************************************************************************************************************************************************************************************************************
ok: [localhost]

TASK [line 1] ********************************************************************************************************************************************************************************************************************************************************************************
--- before
+++ after
@@ -1,4 +1,6 @@
 {
     "file": "pg_hba.conf",
-    "pg_hba": []
+    "pg_hba": [
+        "hostssl\tbug\tbug\t66.66.66.66/32\tldap\tldapbindpasswd =\"#BROKEN\""
+    ]
 }

changed: [localhost]

TASK [line 2 breaks line 1] ******************************************************************************************************************************************************************************************************************************************************************
--- before
+++ after
@@ -1,4 +1,6 @@
 {
     "file": "pg_hba.conf",
-    "pg_hba": []
+    "pg_hba": [
+        "hostssl\tbug\tbug2\t66.66.66.66/32\tldap\tldapbindpasswd =\"#BROKEN\""
+    ]
 }

changed: [localhost]

PLAY RECAP ***********************************************************************************************************************************************************************************************************************************************************************************
localhost                  : ok=3    changed=2    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
```
