### ISSUE TITLE
enabling postgres extension fails with "already exists"

### ISSUE THREAD

**Issue by jcgruenhage** [ansible-collections/community.postgresql#421]
##### SUMMARY

We have a task that enables a postgres extension on two databases inside of a postgres instance, and sometimes (but not all of the times), it fails on one of them. Looks like this:

```
TASK [Enable 'uuid-ossp' extension on api-component databases] ***************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: DETAIL:  Key (extname)=(uuid-ossp) already exists.
failed: [ci] (item=a-database) => {"ansible_loop_var": "item", "changed": false, "item": "a-database", "msg": "Management of PostgreSQL extension failed: duplicate key value violates unique constraint \"pg_extension_name_index\"\nDETAIL:  Key (extname)=(uuid-ossp) already exists.\n"}
changed: [ci] => (item=another-database)
```

The task for this looks like this:
```yaml
    - name: Enable 'uuid-ossp' extension on api-component databases
      community.postgresql.postgresql_ext:
        name: uuid-ossp
        db: "{{ item }}"
        login_host: "{{ postgres_unix_socket_path }}"
      loop:
        - "{{ a_database_name }}"
        - "{{ another_database_name }}"
```

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
community.postgresql.postgresql_ext

##### ANSIBLE VERSION
<del>Paste verbatim output from "ansible --version" between quotes</del> Runs in CI, so that's a bit difficult, but it's a debian on which we've installed ansible==6.4.0 and ansible-core==2.13.4. If needed, we can include `ansible --version` in our CI scripts though.

I've skipped a bunch of things that the template requests, because those are fairly redundant with what has already been written above or they are things that aren't really available.

Either way: This is a fairly annoying bug, we've not been able to isolate when it happens yet, we've not seen it on any local deployments, just in CI, and in CI also consistently only for one component. I have no idea what could cause this, but wanted to submit this upstream anyway, to check in whether anyone else has seen this before and also to ask whether anyone would have a hint on what might be causing this?
