### ISSUE TITLE
postgresql_ping with SSL client certificate and private key

### ISSUE THREAD

**Issue by dtma007** [ansible-collections/community.postgresql#424]
I see that `postgresql_ping` supports specifying a `ca_cert` parameter for the root/CA cert.  But I couldn't find a way to specify a client certificate and client private key to connect to to a Postgres server that has `clientcert=verify-full` or `clientcert=verify-ca`.  Is that supported?

**Comment by aleksvagachev** [comment]
@Andersson007 I'm ready to do it.

**Comment by dtma007** [comment]
@Andersson007 @aleksvagachev Thanks so much for your quick response!  

I still think it would be helpful to have the specific parameters for client cert and client private key in `postgresql_ping`, but I just wanted to let you know that I also found another way to specify the parameters by using the existing `connect_params` parameter.

for example. I did this:
```
  community.postgresql.postgresql_ping:
    db: "{{ db_name }}"
    login_host: "{{ db_server }}"
    login_user: "{{ db_user }}"
    login_password: "{{ decoded_pwd }}"
    ca_cert: "{{ db_ssl_root_cert_filename }}"
    connect_params:
      sslcert: "{{ db_ssl_cert_filename }}" 
      sslkey: "{{ db_ssl_key_filename }}" 
  register: result1
```
