### ISSUE TITLE
"postgresql_privs" doesn't appear to respect SSL certificate connection info in "connect_params"

### ISSUE THREAD

**Issue by stephenmelrose** [ansible-collections/community.postgresql#447]
##### SUMMARY

I _think_ I  might have found a bug, but I'm no expert.

I'm trying to setup some PostgreSQL roles on an AWS RDS Aurora cluster. We also connect to said cluster using an application called [Teleport](https://goteleport.com/).

In order to connect, I need to provide 3 connection parameters: `sslrootcert`, `sslcert`, and `sslkey`. This connection method works fine for `postgresql_user`, for `postgresql_membership`, but appears to error for `postgresql_privs`.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
`community.postgresql.postgresql_privs`

##### ANSIBLE VERSION

```paste below
ansible [core 2.14.4]
  config file = /Users/stevemelrose/work/repos/terraform/infrastructure/REDACTED-postgresql-roles/ansible.cfg
  configured module search path = ['/Users/stevemelrose/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/7.4.0/libexec/lib/python3.11/site-packages/ansible
  ansible collection location = /Users/stevemelrose/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.11.3 (main, Apr  7 2023, 19:29:16) [Clang 14.0.0 (clang-1400.0.29.202)] (/usr/local/Cellar/ansible/7.4.0/libexec/bin/python3.11)
  jinja version = 3.1.2
  libyaml = True
```

##### COLLECTION VERSION

```paste below
# /usr/local/Cellar/ansible/7.4.0/libexec/lib/python3.11/site-packages/ansible_collections
Collection           Version
-------------------- -------
community.postgresql 2.3.2
```

##### CONFIGURATION

```paste below
CONFIG_FILE() = /Users/stevemelrose/work/repos/terraform/infrastructure/REDACTED-postgresql-roles/ansible.cfg
HOST_KEY_CHECKING(/Users/stevemelrose/work/repos/terraform/infrastructure/REDACTED-postgresql-roles/ansible.cfg) = False
RETRY_FILES_ENABLED(/Users/stevemelrose/work/repos/terraform/infrastructure/REDACTED-postgresql-roles/ansible.cfg) = False
```

##### OS / ENVIRONMENT

macOS 12.6.5
MacBook Pro (13-inch, 2020, Four Thunderbolt 3 ports)
2.3 GHz Quad-Core Intel Core i7

##### STEPS TO REPRODUCE

A narrowed down example of the code we're running. It's hard to send a full example due to the dependency on Teleport.

```yaml
- name: Create test_redacted_engineer_ro role
  community.postgresql.postgresql_user:
    login_host: "{{ postgresql_host }}"
    login_port: "{{ postgresql_port|int }}"
    login_user: "{{ postgresql_user }}"
    connect_params: "{{ postgresql_connect_params }}"
    ssl_mode: verify-full
    db: redacted
    name: test_redacted_engineer_ro
    password: required_for_ansible_but_irrelevant
    role_attr_flags: NOCREATEROLE,NOCREATEDB,NOBYPASSRLS,LOGIN

- name: Grant the rds_iam group to test_redacted_engineer_ro to allow IAM authentication (disables password)
  community.postgresql.postgresql_membership:
    login_host: "{{ postgresql_host }}"
    login_port: "{{ postgresql_port|int }}"
    login_user: "{{ postgresql_user }}"
    connect_params: "{{ postgresql_connect_params }}"
    ssl_mode: verify-full
    db: redacted
    target_role: test_redacted_engineer_ro
    group: rds_iam

- name: Allow test_redacted_engineer_ro to connect to the redacted database
  community.postgresql.postgresql_privs:
    login_host: "{{ postgresql_host }}"
    login_port: "{{ postgresql_port|int }}"
    login_user: "{{ postgresql_user }}"
    connect_params: "{{ postgresql_connect_params }}"
    ssl_mode: verify-full
    database: redacted
    type: database
    privs: CONNECT
    roles: test_redacted_engineer_ro
```

##### EXPECTED RESULTS

`postgresql_privs` is able to connect to our database using the certificate files passed as per `postgresql_user` and `postgresql_membership`.

##### ACTUAL RESULTS

The following is our code so far. The first 2 statements work fine, the 3rd errors out with the following,

```
Could not connect to database: connection to server at \"teleport.REDACTED\" (REDACTED), port 443 failed: root certificate file \"/Users/stevemelrose/.postgresql/root.crt\" does not exist\nEither provide the file or change sslmode to disable server certificate verification.\n
```

Except this is not the root certificate I'm passing into `connect_params`. Which can see in the `-vvv` output,

```
The full traceback is:
Traceback (most recent call last):
  File "/var/folders/ck/6s0xhxyj0q14rw94347kwt6r0000gp/T/ansible_community.postgresql.postgresql_privs_payload_as6782b9/ansible_community.postgresql.postgresql_privs_payload.zip/ansible_collections/community/postgresql/plugins/modules/postgresql_privs.py", line 1134, in main
  File "/var/folders/ck/6s0xhxyj0q14rw94347kwt6r0000gp/T/ansible_community.postgresql.postgresql_privs_payload_as6782b9/ansible_community.postgresql.postgresql_privs_payload.zip/ansible_collections/community/postgresql/plugins/modules/postgresql_privs.py", line 549, in __init__
  File "/usr/local/Cellar/ansible/7.4.0/libexec/lib/python3.11/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.OperationalError: connection to server at "REDACTED" (REDACTED), port 443 failed: root certificate file "/Users/stevemelrose/.postgresql/root.crt" does not exist
Either provide the file or change sslmode to disable server certificate verification.

fatal: [localhost]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "ca_cert": null,
            "connect_params": {
                "sslcert": "/Users/stevemelrose/.tsh/keys/REDACTED/steve@REDACTED.com-db/REDACTED/REDACTED-x509.pem",
                "sslkey": "/Users/stevemelrose/.tsh/keys/REDACTED/steve@REDACTED.com",
                "sslrootcert": "/Users/stevemelrose/.tsh/keys/REDACTED/cas/REDACTED.pem"
            },
            "database": "REDACTED",
            "fail_on_role": true,
            "grant_option": null,
            "host": "REDACTED",
            "login": "REDACTED_admin",
            "login_host": "REDACTED",
            "login_password": "",
            "login_port": "443",
            "login_unix_socket": "",
            "login_user": "REDACTED_admin",
            "objs": null,
            "password": "",
            "port": 443,
            "privs": "CONNECT",
            "roles": "test_REDACTED_engineer_ro",
            "schema": null,
            "session_role": null,
            "ssl_mode": "verify-full",
            "state": "present",
            "target_roles": null,
            "trust_input": true,
            "type": "database",
            "unix_socket": "",
            "usage_on_types": true
        }
    },
    "msg": "Could not connect to database: connection to server at \"REDACTED\" (REDACTED), port 443 failed: root certificate file \"/Users/stevemelrose/.postgresql/root.crt\" does not exist\nEither provide the file or change sslmode to disable server certificate verification.\n"
}
```
