### ISSUE TITLE
Postgresql_user not indempotent fails when re-run playbook as database is deleted.

### ISSUE THREAD

**Issue by mdiogene** [ansible-collections/community.postgresql#459]
##### SUMMARY

The module postgresql_user is notindepotent, it fails when the playbook is re-executed.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

postgresql_user

##### ANSIBLE VERSION

```shell
ansible [core 2.14.1]

```

##### COLLECTION VERSION

```shell
# /usr/local/lib/python3.9/dist-packages/ansible_collections
Collection           Version
-------------------- -------
community.postgresql 2.3.1  

# /usr/lib/python3/dist-packages/ansible_collections
Collection           Version
-------------------- -------
community.postgresql 1.1.1

```

##### CONFIGURATION

```shell
CONFIG_FILE() = None
```

##### OS / ENVIRONMENT

CentOS 7

##### STEPS TO REPRODUCE

```yaml
- name: "Delete user {{ item.name }}"
  postgresql_user:
    db: "{{ CURRENT_USER_REMOVE.name }}"
    name: "{{ item.name }}"
    priv: "{{ item.priv }}"
    state: absent
  with_items:
    - "{{ CURRENT_USER_REMOVE.user }}"
  tags: delete_user
```

##### EXPECTED RESULTS

The playbook must not failed when re-run (after database deletion)

##### ACTUAL RESULTS

failed: [sv-pdb] (item={'name': 'antho', 'priv': 'ALL'}) => {"ansible_loop_var": "item", "changed": false, "item": {"name": "antho", "priv": "ALL"}, "msg": "unable to connect to database: la connexion au serveur sur le socket « /var/run/postgresql/.s.PGSQL.5432 » a échoué : FATAL:  la base de données « HISTOIRE » n'existe pas\n"}

```paste below

```
