### ISSUE TITLE
postgresql_query fails with 'can't execute an empty query' when a commented out query is present in the script

### ISSUE THREAD

**Issue by nodiscc** [ansible-collections/community.postgresql#50]
##### SUMMARY

When trying to run [this script](https://git.tt-rss.org/fox/tt-rss/src/branch/master/schema/ttrss_schema_pgsql.sql) through `postgresql_query` using `path_to_script`, the module fails with

```
Cannot execute SQL: -- create index ttrss_entries_title_index on ttrss_entries(title)' None: can't execute an empty query, query list:
[...]
```

Deleting the commented-out query line 164 makes the module work again.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

`posqtgresql_query`

##### ANSIBLE VERSION

```paste below
ansible 2.10.5
  config file = None
  configured module search path = ['/home/live/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/live/.local/share/xsrv/venv/lib/python3.7/site-packages/ansible
  executable location = /home/live/.local/share/xsrv/venv/bin/ansible
  python version = 3.7.3 (default, Jul 25 2020, 13:03:44) [GCC 8.3.0]

```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

- Debian 10 Buster on host and controller
- postgresql 11+200+deb10u4

##### STEPS TO REPRODUCE

```yaml
# playbook.yml
- hosts: my.EXAMPLE.org
  roles:
    - tt_rss

# roles/tt_rss/tasks/main.yml
- include: tt-rss.yml
  become: yes

# roles/tt_rss/tasks/tt-rss.yml
- name: install postgresql
  apt:
    state: present
    package:
      - postgresql
      - postgresql-client

- name: install packages for postgresql support
  apt:
    state: present
    package:
      - php-pgsql
      - python3-psycopg2

- name: create tt-rss postgresql user
  become: yes
  become_user: postgres
  postgresql_user:
    name: "ttrss"
    state: present

- name: set tt-rss postgresql user password
  become: yes
  become_user: postgres
  postgresql_user:
    name: "ttrss"
    password: "CHANGEME"
  no_log: True

- name: create tt-rss postgresql database
  become: yes
  become_user: postgres
  postgresql_db:
    name: "ttrss"
    state: present
    encoding: 'UNICODE'
    owner: 'ttrss'

- name: grant privileges on tt-rss database to tt-rss postgresql user
  become: yes
  become_user: postgres
  postgresql_privs:
    db: "ttrss"
    privs: ALL
    type: database
    role: "ttrss"

- name: clone/upgrade tt-rss
  git:
    repo: https://git.tt-rss.org/git/tt-rss.git
    dest: "/var/www/rss.EXAMPLE.org"
    version: 'master'
    accept_hostkey: yes
    force: yes

- name: import tt-rss database schema to postgresql
  postgresql_query:
    login_host: "localhost"
    login_user: "ttrss"
    login_password: "CHANGEME"
    db: "ttrss"
    path_to_script: "/var/www/rss.EXAMPLE.org/schema/ttrss_schema_pgsql.sql"


```

##### EXPECTED RESULTS

The commented out line should be ignored and the script should execute correctly. Note that running the script with `sudo -u postgres psql --file=/var/www/rss.EXAMPLE.org/schema/ttrss_schema_pgsql.sql` works without problems.

##### ACTUAL RESULTS

```paste below
$ ansible-playbook playbook.yml

[...]

TASK [tt_rss : import tt-rss database schema to postgresql] *************************************************************************************************************
fatal: [my.EXAMPLE.org]: FAILED! => {
    "changed": false
}

MSG:

Cannot execute SQL '

-- create index ttrss_entries_title_index on ttrss_entries(title)' None: can't execute an empty query, query list: ['drop table if exists ttrss_error_log', '\ndrop table if exists ttrss_plugin_storage', '\ndrop table if exists ttrss_linked_feeds', '...................
```

Inserting the following task before `import tt-rss database schema to postgresql` makes the playbook work again:

```yaml
- name: remove comments from SQL schema file
  lineinfile:
    path: "{{ tt_rss_install_dir }}/schema/ttrss_schema_pgsql.sql"
    state: absent
    regexp: '^--.*'
```
