### ISSUE TITLE
Enable integration testing of postgresql_lang

### ISSUE THREAD

**Issue by elpavel** [ansible-collections/community.postgresql#519]
##### SUMMARY
Tests for module postgresql_lang run only on CentOS 7.
Integration testing of the lang module should be enabled on all targets, to cover the various os/python/postgres/psycopg/ansible versions. 

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
postgresql_lang

##### ADDITIONAL INFORMATION

See https://github.com/ansible-collections/community.postgresql/blob/main/tests/integration/targets/postgresql_lang/tasks/main.yml#L16
```yaml
- name: Initial CI tests of postgresql_lang module
  when:
    - ansible_facts.distribution == 'CentOS'
    - ansible_facts.distribution_major_version is version ('7', '==')
```
