### ISSUE TITLE
Dropping a tablespace using postgresql_tablespace fails if the tablespace does not exist

### ISSUE THREAD

**Issue by andreasscherbaum** [ansible-collections/community.postgresql#547]
##### SUMMARY

When using the `postgresql_tablespace` module to drop a tablespace, this fails if the tablespace does not exist.

```
TASK [Drop TABLESPACEs] **********************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Tries to drop nonexistent tablespace 'testtablespace'"}
```

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

postgresql_tablespace

##### ANSIBLE VERSION

```paste below
ansible [core 2.14.2]
  config file = None
  configured module search path = ['/home/ads/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  ansible collection location = /home/ads/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.11.4 (main, Jun  9 2023, 07:59:55) [GCC 12.3.0] (/usr/bin/python3)
  jinja version = 3.1.2
  libyaml = True
```

##### COLLECTION VERSION

```paste below
# /home/ads/.ansible/collections/ansible_collections
Collection        Version
----------------- -------
community.general 3.1.0  

# /usr/lib/python3/dist-packages/ansible_collections
Collection        Version
----------------- -------
community.general 6.3.0  

# /usr/lib/python3/dist-packages/ansible_collections
Collection           Version
-------------------- -------
community.postgresql 2.3.2  
```

##### CONFIGURATION

```paste below
CONFIG_FILE() = None
```

##### OS / ENVIRONMENT

This is an Ubuntu 23.04 installation:
```
ii  ansible                                        7.2.0+dfsg-2                                all          Configuration management, deployment, and task execution system
ii  ansible-core                                   2.14.2-1                                    all          Configuration management, deployment, and task execution system
ii  ansible-lint                                   6.13.1-1ubuntu1                             all          lint tool for Ansible playbooks
ii  python3-ansible-compat                         3.0.1-1                                     all          Ansible compatibility goodies
```

##### STEPS TO REPRODUCE

```yaml
---

- name: Create Tablespace
  hosts: localhost
  gather_facts: True
  become: no
  any_errors_fatal: True
  force_handlers: True
  tasks:

    - name: Create tablespace directory
      ansible.builtin.file:
        path: "/var/lib/postgresql/tablespace-test"
        state: directory
        owner: postgres
        group: postgres
        mode: "0700"
      become: yes
      become_user: postgres


    - name: Create TABLESPACEs
      community.postgresql.postgresql_tablespace:
        db: "postgres"
        owner: "postgres"
        name: "testtablespace"
        location: "/var/lib/postgresql/tablespace-test"
        state: present
      become: yes
      become_user: postgres
      # comment this out for creating the tablespace
      when: 0 == 1


    # check with \db if the tablespace exists


    - name: Wait 10 seconds
      ansible.builtin.pause:
        seconds: 10


    - name: Drop TABLESPACEs
      community.postgresql.postgresql_tablespace:
        db: "postgres"
        name: "testtablespace"
        state: absent
      become: yes
      become_user: postgres
      # remove this comment for using the next task
      #when: 0 == 1


    - name: Drop Tablespace
      community.postgresql.postgresql_query:
        db: "postgres"
        query: "DROP TABLESPACE IF EXISTS \"testtablespace\""
        autocommit: yes
      changed_when: False
      become: yes
      become_user: postgres
```

##### EXPECTED RESULTS

The expected behavior is that `state: absent` does not fail if and when the tablespace does not exist.

##### ACTUAL RESULTS

```paste below
TASK [Drop TABLESPACEs] **********************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Tries to drop nonexistent tablespace 'testtablespace'"}
```
