### ISSUE TITLE
Support for number of jobs in target_opts

### ISSUE THREAD

**Issue by PieterPaulussen** [ansible-collections/community.postgresql#594]
##### SUMMARY
Support multiple sessions for `pg_restore` & make use of regular file.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
community.postgresql.postgresql_db:

##### ADDITIONAL INFORMATION
When using the additional "--jobs" argument, you will get the following error:
```
"msg": "pg_restore: error: parallel restore from standard input is not supported"
```

```yaml
- name: Restore the database from ~/db_dump.pgc
  community.postgresql.postgresql_db:
    name: foo
    state: restore
    target: ~/db_dump.pgc
    login_user: user_name
    login_password: user_pass
    target_opts: "--jobs=4"
```
