### ISSUE TITLE
customising login_unix_socket is not working

### ISSUE THREAD

**Issue by nskalis** [ansible-collections/community.postgresql#65]
##### SUMMARY
When trying to adjust the `login_unix_socket` option
```
      - set_fact: postgresql_conn="/tmp/.s.PGSQL.{{ item.port }}"
        with_items:
          - "{{ postgresql_config.app[instance] }}"
```

The modules `community.postgresql.postgresql_db` and `community.postgresql.postgresql_user` (at least) ignore the full path and append the default setting unix socket `.s.PGSQL.5432`. 
As a result, the error below manifests

```
TASK [Create new databases] **************************************************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: 	connections on Unix domain socket "/tmp/.s.PGSQL.5433/.s.PGSQL.5432"?
failed: [light-20-pro] (item=pmacct) => {"ansible_loop_var": "item", "changed": false, "item": "pmacct", "msg": "unable to connect to database: could not connect to server: Not a directory\n\tIs the server running locally and accepting\n\tconnections on Unix domain socket \"/tmp/.s.PGSQL.5433/.s.PGSQL.5432\"?\n"}
```

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
- community.postgresql.postgresql_db
- community.postgresql.postgresql_user

##### ANSIBLE VERSION

```paste below
> ansible --version
ansible 2.10.5
  config file = /home/xxx/ip-spotlight/ansible/ansible.cfg
  configured module search path = ['/home/xxx/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/xxx/.pyenv/versions/3.8.7/lib/python3.8/site-packages/ansible
  executable location = /home/xxx/.pyenv/versions/3.8.7/bin/ansible
  python version = 3.8.7 (default, Feb 13 2021, 11:13:05) [GCC 7.5.0]
```

##### CONFIGURATION

```paste below
DEFAULT_HOST_LIST(/home/app/ip-spotlight/ansible/ansible.cfg) = ['/home/xxx/ip-spotlight/ansible/hosts']
DEFAULT_JINJA2_EXTENSIONS(/home/xxx/ip-spotlight/ansible/ansible.cfg) = jinja2.ext.do,jinja2.ext.i18n,jinja2.ext.loopcontrols
INTERPRETER_PYTHON(/home/xxx/ip-spotlight/ansible/ansible.cfg) = ~/.pyenv/shims/python
```

##### OS / ENVIRONMENT

```
> hostnamectl
   Static hostname: light-00-micro
         Icon name: computer-vm
           Chassis: vm
        Machine ID: c88688bb337042c3b0842a372753675f
           Boot ID: 583af949666640e59b22e6ac33e8ed14
    Virtualization: vmware
  Operating System: openSUSE Leap 15.2
       CPE OS Name: cpe:/o:opensuse:leap:15.2
            Kernel: Linux 5.3.18-lp152.63-default
      Architecture: x86-64
```

##### STEPS TO REPRODUCE

```yaml
      - set_fact: postgresql_conn="/tmp/.s.PGSQL.{{ item.port }}"
        with_items:
          - "{{ postgresql_config.app[instance] }}"

      - name: "Create new databases"
        become_user: postgres
        community.postgresql.postgresql_db: login_unix_socket="{{ postgresql_conn }}" name="{{ item }}" state=present template="template0" encoding="UTF-8" lc_collate="en_US.UTF-8" lc_ctype="en_US.UTF-8"
        with_items:
          - pmacct

      - name: "Add the database user"
        become_user: postgres
        community.postgresql.postgresql_user: login_unix_socket="{{ postgresql_conn }}" name="{{ username }}" encrypted=yes password="{{ database.password }}" role_attr_flags=SUPERUSER,NOINHERIT,CREATEROLE,CREATEDB,LOGIN,REPLICATION state=present 

```

##### EXPECTED RESULTS

Unix domain socket should be set to
```
/tmp/.s.PGSQL.5433
```

##### ACTUAL RESULTS

```paste below
/tmp/.s.PGSQL.5433/.s.PGSQL.5432
```

**Comment by Andersson007** [comment]
@nskalis thanks for the report!

I don't see the connection function (common for all the modules) appends anything.

I think you could try to specify just `/tmp` as explained here https://stackoverflow.com/questions/5500332/cant-connect-the-postgresql-with-psycopg2

Also https://www.postgresql.org/docs/current/runtime-config-connection.html i can see the parameter called `unix_socket_directories (string)` and no options like `unix_socket`. I think postgres itself think that `/tmp/.s.PGSQL.5433` you passed is a directory and tries to find a socket there appending the default one.

Could you please try to pass just `/tmp` to `login_unix_socket` and give feedback?

**Comment by nskalis** [comment]
Thank you for looking into it. This is what I did to make it work:

1. changed the path to `/tmp`
2. changed the port (to its original): `5432` (from `5433`)

The above works. But, I don't know how to make it work using the non-default port.

**Comment by Andersson007** [comment]
Good question.
Anyway, i think the issue is out of scope of the collection.

I found https://serverfault.com/questions/260229/postgres-application-tries-to-use-incorrect-socket-file with similar symptoms.

According to the suggested, you could use https://docs.ansible.com/ansible/latest/user_guide/playbooks_environment.html and try to add to your tasks the `environment` option specifying the port, e.g.:
```
      - name: "Add the database user"
        become_user: postgres
        community.postgresql.postgresql_user: ...
        environment:
          PGPORT: 5433
```

Please give the feedback, just interesting:)
