### ISSUE TITLE
postgresql_db dump gives incorrect error 'password authentication failed' 

### ISSUE THREAD

**Issue by asifiqbal** [ansible-collections/community.postgresql#66]
##### SUMMARY

When no permission to write on target during dump, postgresql_db gives wrong error message "FATAL:  password authentication failed for user". It works fine when become: yes

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

```yaml
postgresql_db:
   name: acme
   state: dump
   target: /mnt/postgres/backup/acme.sql.gz
```
##### ANSIBLE VERSION

```paste below
ansible 2.9.13
  config file = /data/asif/ansible/ansible.cfg
  configured module search path = ['/home/acag-asif.iqbal/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.6/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.6.8 (default, Aug 13 2020, 07:46:32) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]

```

##### CONFIGURATION

```paste below
DEFAULT_CALLBACK_WHITELIST(/data/asif/ansible/ansible.cfg) = ['profile_roles', 'profile_tasks', 'timer', 'default']
DEFAULT_HOST_LIST(/data/asif/ansible/ansible.cfg) = ['/data/asif/ansible/hosts']
DEFAULT_ROLES_PATH(/data/asif/ansible/ansible.cfg) = ['/data/asif/ansible/roles']
DEFAULT_VAULT_PASSWORD_FILE(/data/asif/ansible/ansible.cfg) = /data/asif/ansible/my-vault-pass

```

##### OS / ENVIRONMENT

$ cat /etc/redhat-release                                                     
Red Hat Enterprise Linux Server release 7.9 (Maipo)

##### STEPS TO REPRODUCE

$ ansible-playbook --tags database playbooks/dev/jira_refresh.yml

```yaml
- hosts: jira_dev
  gather_facts: no
  become: yes

  tasks:
   - name: Stop jira
     service: 
       name: jira
       state: stopped
     tags: stop


- hosts: localhost
  connection: local
  gather_facts: no
  tags: database

  vars:
    IAM_user: db-user-asif.iqbal
    IAM_profile: dbuser
    UPDATE_DB: no
    DB: testdb

  roles:
    - role: jira_refresh_db
      vars:
        RDSHOST: "{{ PGHOSTS.dev }}"


- hosts: jira_dev
  gather_facts: no
  become: yes
  tags: filesystem

  roles:
    - role: jira_refresh_filesystem

```

##### EXPECTED RESULTS

When I uncomment become: yes, the task runs fine.
```yaml
- name: Backup the original database {{ DB }}
  postgresql_db:
    name: jira
    state: dump
    target: "{{ DB_BACKUP_BASE_DIR }}/jira/jira_orig.sql.gz"
    login_user: jirauser
    login_password: "{{ JIRA_DB_PASS }}"
    login_host: "{{ RDSHOST }}"
  #become: yes
```
##### ACTUAL RESULTS

```paste below
TASK [jira_refresh_db : Backup the original database testdb] *******************************************************
task path: /data/asif/ansible/roles/jira_refresh_db/tasks/main.yml:26
Thursday 11 March 2021  20:13:10 +0000 (0:00:00.104)       0:00:01.780 ******** 
Thursday 11 March 2021  20:13:10 +0000 (0:00:00.104)       0:00:01.778 ******** 
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: acag-asif.iqbal
<127.0.0.1> EXEC /bin/sh -c 'echo ~acag-asif.iqbal && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/acag-asif.iqbal/.ansible/tmp `"&& mkdir "` echo /home/acag-asif.iqbal/.ansible/tmp/ansible-tmp-1615493590.206678-29943-142257380365820 `" && echo ansible-tmp-1615493590.206678-29943-142257380365820="` echo /home/acag-asif.iqbal/.ansible/tmp/ansible-tmp-1615493590.206678-29943-142257380365820 `" ) && sleep 0'
Using module file /usr/local/lib/python3.6/site-packages/ansible/modules/database/postgresql/postgresql_db.py
<127.0.0.1> PUT /home/acag-asif.iqbal/.ansible/tmp/ansible-local-298981a9mp82i/tmpbibqzmsg TO /home/acag-asif.iqbal/.ansible/tmp/ansible-tmp-1615493590.206678-29943-142257380365820/AnsiballZ_postgresql_db.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /home/acag-asif.iqbal/.ansible/tmp/ansible-tmp-1615493590.206678-29943-142257380365820/ /home/acag-asif.iqbal/.ansible/tmp/ansible-tmp-1615493590.206678-29943-142257380365820/AnsiballZ_postgresql_db.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/usr/bin/python3 /home/acag-asif.iqbal/.ansible/tmp/ansible-tmp-1615493590.206678-29943-142257380365820/AnsiballZ_postgresql_db.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'rm -f -r /home/acag-asif.iqbal/.ansible/tmp/ansible-tmp-1615493590.206678-29943-142257380365820/ > /dev/null 2>&1 && sleep 0'
fatal: [localhost]: FAILED! => {
    "changed": false,
    "cmd": "/usr/bin/gzip </home/acag-asif.iqbal/.ansible/tmp/ansible-tmp-1615493590.206678-29943-142257380365820/pg_fifo > /mnt/postgres/backup/jira/jira_orig.sql.gz & /usr/bin/pg_dump jira --host=mstd-aurora-postgresauroracluste.rds.amazonaws.com --port=5432 --username=jirauser >/home/acag-asif.iqbal/.ansible/tmp/ansible-tmp-1615493590.206678-29943-142257380365820/pg_fifo",
    "invocation": {
        "module_args": {
            "ca_cert": null,
            "conn_limit": "",
            "db": "jira",
            "encoding": "",
            "lc_collate": "",
            "lc_ctype": "",
            "login_host": "mstd-aurora-postgresauroracluster.rds.amazonaws.com",
            "login_password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "login_unix_socket": "",
            "login_user": "jirauser",
            "maintenance_db": "postgres",
            "name": "jira",
            "owner": "",
            "port": 5432,
            "session_role": null,
            "ssl_mode": "prefer",
            "state": "dump",
            "tablespace": "",
            "target": "/mnt/postgres/backup/jira/jira_orig.sql.gz",
            "target_opts": "",
            "template": ""
        }
    },
    "msg": "/bin/sh: /mnt/postgres/backup/jira/jira_orig.sql.gz: Permission denied\npg_dump: [archiver (db)] connection to database \"jira\" failed: FATAL:  password authentication failed for user \"jirauser\"\nFATAL:  password authentication failed for user \"jirauser\"\n",
    "rc": 1,
    "stdout": "",
    "stdout_lines": []
}

```
