### ISSUE TITLE
Allow specifying schema in the db module

### ISSUE THREAD

**Issue by StyXman** [ansible-collections/community.postgresql#696]
##### SUMMARY
PG allows splitting tables into schemas https://www.postgresql.org/docs/current/ddl-schemas.html but the db module does not allow to specify them.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
postgres_db plugin/module.

##### ADDITIONAL INFORMATION
```yaml
  - name: Create DBs
    community.postgresql.postgresql_db:
      schema: foo
      name:  bar
```

Will try to come up with a patch myself, as I'm gonna implement it locally, at least as a hack.
