### ISSUE TITLE
Idempotency Issue with community.postgresql.postgresql_subscription Module

### ISSUE THREAD

**Issue by YuriiBudnyi** [ansible-collections/community.postgresql#703]
##### SUMMARY

NOTE: it's about **AWS RDS Postgres**

Hello Team.
I need assistance with the community.postgresql.postgresql_subscription module. I use this module to create a subscription in an AWS RDS Postgres 15.5 instance. The first run of the playbook works perfectly, and the subscription is created without any issues. However, when I run the same playbook a second time, I receive the following error:

`Cannot execute SQL 'CREATE SUBSCRIPTION "subscription_name"
    CONNECTION
    'host=example.rds.amazonaws.com
    port=5432 user=...password=...
    dbname=...' PUBLICATION "pub_name" WITH
    (slot_name = 'slot_name')': subscription "subscription_name"
    already exists
`
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

community.postgresql.postgresql_subscription v3.2.0
##### ANSIBLE VERSION

```paste below
Ansible 2.15.0
```

##### COLLECTION VERSION

```paste below
community.postgresql.postgresql_subscription v3.2.0
```

##### STEPS TO REPRODUCE

```yaml
- name: Create subscription
  community.postgresql.postgresql_subscription:
    db: "{{ database_name }}"
    name: "\"{{ subscription_name }}\""
    state: present
    publications: "\"{{ publication_name }}\""
    login_user: "{{ login_user }}"
    login_host: "{{ login_host }}"
    login_password: "{{ login_password }}"
    port: "{{ port }}"
    subsparams:
      slot_name: "'{{ slot_name }}'"
    connparams:
      host: "{{ replication_host }}"
      port: "{{ replication_port }}"
      user: "{{ replication_user }}"
      password: "{{ replication_passwd }}"
      dbname: "{{ replication_db }}"
```

##### EXPECTED RESULTS

playbook result should be idempotent

##### ACTUAL RESULTS

Issue that subscription "subscription_name" already exists

```paste below

```
