### ISSUE TITLE
Create postgresql_domain module

### ISSUE THREAD

**Issue by arcturustech** [ansible-collections/community.postgresql#706]
##### SUMMARY

This would be a new module to manage domains. Interface would be exactly analogous to postgresql.ext, postgresql.schema, or many others that manage create, drop and alter of 
major postgres objects 

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

postgresql_domain
##### ADDITIONAL INFORMATION

There is currently no easy or obvious way to manage domains idempotently in ansible playbooks, the way there now is for tables, schemas, extensions,  etc.

Domains are a puzzling exception to the wonderful way almost all other postgres objects can be managed in ansible. Without this, I will have to fall back on raw queries through the query module, and manage idempotence manually

```yaml
    - name: Create a COUNT domain in the INVENTORY schema
      become_user: postgres
      community.postgresql.postgresql_domain:
        name: "COUNT"
        db: "WIDGET_INC"
        schema: "INVENTORY"
        base_type: "INT"
        check: "VALUE >= 0"
        cascade: true
        comment: "Domains are a great, underused tool for code readability and maintainability"
        state: present
```

**Comment by Andersson007** [comment]
@arcturustech hello, thanks for opening the issue!
Does a separate module bring any value compared to using just the `postgresql_query` module?
Specifically, can it provide **full** idempotency?
I know there are some modules (like postgresql_table, _idx, etc.) that don't work fully idempotently and it's partly my fault due to not being experienced at that time but imo there shouldn't be modules like that.
I'm not a user so why I'm asking this because I don't know.
For example, if we create a domain using the task from the description and later change any of the arguments values, will the module change the object to match the new state or it's impossible w/o destroying the object and re-creating it from scratch?

What do others think?
Thanks

**Comment by hunleyd** [comment]
iirc, renaming a domain is the only altering you can do w/o dropping and recreating

**Comment by Andersson007** [comment]
> iirc, renaming a domain is the only altering you can do w/o dropping and recreating

@hunleyd thanks! in this case, i would suggest using `postgresql_query` instead of adding another module

**Comment by arcturustech** [comment]
> iirc, renaming a domain is the only altering you can do w/o dropping and recreating

Actually the postgres ALTER DOMAIN statement (as of the current version 16) is pretty complete, as per the official documentation: https://www.postgresql.org/docs/current/sql-alterdomain.html

As you can see, pretty much every parameter of a DOMAIN can be altered without dropping and recreating

**Comment by hunleyd** [comment]
I should have been clearer, you cannot change a constraint w/o dropping the existing constraint and adding the new one, and you cannot change the base type w/o dropping the domain itself. You can:
```
-    { SET DEFAULT expression | DROP DEFAULT }
-    { SET | DROP } NOT NULL
-    ADD domain_constraint [ NOT VALID ]
-    DROP CONSTRAINT [ IF EXISTS ] constraint_name [ RESTRICT | CASCADE ]
-    RENAME CONSTRAINT constraint_name TO new_constraint_name
-    VALIDATE CONSTRAINT constraint_name
-    OWNER TO { new_owner | CURRENT_ROLE | CURRENT_USER | SESSION_USER }
-    RENAME TO new_name
-    SET SCHEMA new_schema
```
which means of the proposed module args both:
```
-        base_type: "INT"
-        check: "VALUE >= 0"
```
cannot be changed, which to me seems to be a the 'base functionality' of the proposed module.

Having said that, I happily defer to others on the matter.

**Comment by arcturustech** [comment]
It's true that you cannot alter the base type of a domain. Presumably this is because doing so would make no sense, and it's not something a developer should ever want to do. A domain is by definition a subset of another datatype - the base datatype is fundamental to what the domain _is_ and should not be changeable. So I understand why the postgres team did not provide for this and likely never would.

The constraints (note plural) really are the heart of what you need to be able to alter to make domains useful, as they define the subset. Those alterations take two basic forms - contracting the domain subset (by adding a constraint) and expanding the domain subset (by removing a constraint).

Initially, my example has one constraint (value >=0). If I later decide that no COUNT should be too large (restrict the subset), it's true I can't change constraint1 to (value >= 0 and value < 1000) but I can certainly use ALTER CONSTRAINT to add a second, independent constraint2 (value < 1000). If I then decide that 0 value COUNT is also unacceptable, I simply add constraint3 (value > 0). At that point constraint1 (value >= 0) is still applicable, just always overridden by constraint3. I could then remove constraint1, but I don't have to and probably wouldn't, as it will then still be there doing it's job if I ever remove constraint3. Meanwhile, once I realize that constraint2 was a bad idea, I can remove it independently (expand the subset)

The important thing is that I can massage the constraint to provide any subset of the base datatype that I need _without_ having to drop and re-create the domain (and worse yet every table that depends on that domain).

So does this count as having to drop and re-create the domain itself? That would seem to depend on the logic of why drop and re-create would be considered an anti-pattern and whether that logic still applies to this situation. That is something I don't fully understand, and at any rate you will have to decide for yourself.

**Comment by hunleyd** [comment]
Given the following:
```
    - name: Create a COUNT domain in the INVENTORY schema
      become_user: postgres
      community.postgresql.postgresql_domain:
        name: "COUNT"
        db: "WIDGET_INC"
        schema: "INVENTORY"
        base_type: "INT"
        check: "VALUE >= 0"
        default: 0
        cascade: false
        comment: "Domains are a great, underused tool for code readability and maintainability"
        state: present
```
[time passes]
```
    - name: Create a COUNT domain in the INVENTORY schema
      become_user: postgres
      community.postgresql.postgresql_domain:
        name: "COUNT"
        db: "WIDGET_INC"
        schema: "INVENTORY"
        base_type: "INT"
        check: "VALUE < 1000"
        default: 0
        cascade: false
        comment: "Domains are a great, underused tool for code readability and maintainability"
        state: present
```
how would the module know that this is an additional constraint and not a desire to replace the existing constraint?
