### ISSUE TITLE
postgresql user has not permission on public schema

### ISSUE THREAD

**Issue by asarubbo** [ansible-collections/community.postgresql#716]
##### SUMMARY
I'm migrating [sonarqube](https://www.sonarsource.com/products/sonarqube/) from CentOS-7 to Rocky-9.
On CentOS-7 the postgresql version is `9.6.20` while on Rocky-9 is `13.14-1`
The playbook is the same.

So I'm managing that stuff with:
```
    - name: Create sonarqube postgresql user
      postgresql_user:
        name: sonarqube
        password: sonarqube
      become: true
      become_user: postgres

    - name: Create sonarqube postgresql database
      postgresql_db:
        name: sonarqube
        owner: sonarqube
        encoding: UTF-8
      become: true
      become_user: postgres

    - name: Grant
      postgresql_user:
        db: sonarqube
        name: sonarqube
        password: sonarqube
        role_attr_flags: LOGIN
        priv: ALL
      become: true
      become_user: postgres
```

This has the following (expected) effects on CentOS-7:

```
 ~ # PAGER="cat" psql -U sonarqube -d sonarqube -c "\dt"
                   List of relations
 Schema |           Name            | Type  |   Owner   
--------+---------------------------+-------+-----------
 public | active_rule_parameters    | table | sonarqube
<snip>
```

While it has this unexpected effects on Rocky-9:
```
 ~ # PAGER="cat" psql -U sonarqube -d sonarqube -c "\dt"
Did not find any relations.
```

While trying to find out where the issue is, I discovered that the following command fixes the issue:

```
psql -U postgres -d sonarqube -c "GRANT USAGE ON SCHEMA public TO sonarqube;"
```

So my issues atm are:

1) Is expected to have this behavior?
2) I didn't find a way to translate the above command into a `postgresql_privs` task

How to get a user that by default has a permission on the public schema?

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
postgresql_privs
postgresql_user

##### ANSIBLE VERSION

```
ansible [core 2.16.5]
  config file = /home/ago/.ansible.cfg
  configured module search path = ['/home/ago/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.11/site-packages/ansible
  ansible collection location = /home/ago/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/lib/python-exec/python3.11/ansible
  python version = 3.11.9 (main, May 16 2024, 12:35:36) [GCC 13.2.1 20240210] (/usr/bin/python3.11)
  jinja version = 3.1.3
  libyaml = True
```

##### COLLECTION VERSION

```
# /usr/lib/python3.11/site-packages/ansible_collections
Collection        Version
----------------- -------
community.general 8.5.0 
```

##### CONFIGURATION

```
ACTION_WARNINGS(/home/ago/.ansible.cfg) = False
CONFIG_FILE() = /home/ago/.ansible.cfg
DEFAULT_FORKS(/home/ago/.ansible.cfg) = 30
DEFAULT_HOST_LIST(/home/ago/.ansible.cfg) = ['/home/ago/git/ansible/common/hosts']
DEFAULT_REMOTE_USER(/home/ago/.ansible.cfg) = root
DEPRECATION_WARNINGS(/home/ago/.ansible.cfg) = False
EDITOR(env: EDITOR) = nano
HOST_KEY_CHECKING(/home/ago/.ansible.cfg) = False
INTERPRETER_PYTHON(/home/ago/.ansible.cfg) = auto_legacy_silent
PAGER(env: PAGER) = /usr/bin/less
```

##### OS / ENVIRONMENT
Gentoo x86_64

**Comment by Andersson007** [comment]
@asarubbo hello, thanks for reporting the issue.
In the [latest collection docs](https://docs.ansible.com/ansible/devel/collections/community/postgresql/postgresql_privs_module.html) I found the `GRANT ALL PRIVILEGES ON SCHEMA public, math TO librarian` example.
I modified it:
```
- name: Try this
  community.postgresql.postgresql_privs:
    db: YOURDB
    privs: USE
    type: schema
    objs: public
    role: sonarqube
```
Could you try it and say if it works or not?
