### ISSUE TITLE
community.postgresql.postgresql_pg_hba: not writting to pg_hba.conf overwritting the lines for the same user

### ISSUE THREAD

**Issue by carcuevas** [ansible-collections/community.postgresql#730]
##### SUMMARY
Somehow when using ~contype hostnossl is being translated to hostssl...~  different lines of configuration but using the same user, it will overwrite the lines already changed and it will just keep the last one.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
      community.postgresql.postgresql_pg_hba

##### ANSIBLE VERSION

```
ansible [core 2.17.3]
  config file = /Users/user1/repos/ansible/ansible.cfg
  configured module search path = ['/Users/user1/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/user1/Library/Python/3.12/lib/python/site-packages/ansible
  ansible collection location = /Users/user1/.ansible/collections:/usr/share/ansible/collections
  executable location = /Users/user1/Library/Python/3.12/bin/ansible
  python version = 3.12.6 (main, Sep  7 2024, 05:59:21) [Clang 13.0.0 (clang-1300.0.29.3)] (/opt/local/Library/Frameworks/Python.framework/Versions/3.12/bin/python3.12)
  jinja version = 3.1.4
  libyaml = True
```

##### COLLECTION VERSION
```
# /Users/user1/Library/Python/3.12/lib/python/site-packages/ansible_collections
Collection        Version
----------------- -------
community.general 9.3.0

```

##### OS / ENVIRONMENT
MacOS BigSur and Sonoma

##### STEPS TO REPRODUCE
Actually when executing this

```yaml


    - name: Configuring pg_hba
      community.postgresql.postgresql_pg_hba:
        dest: "{{ postgresql_cfg_hba_file }}"
        mode: "0755"
        create: true
        contype: "{{ item.contype }}"
        databases: all
        source: "0.0.0.0/0" 
        users: "{{ item.users }}"
        method: "{{ item.method }}"
      notify: Reload_postgresql
      loop: [ { users: "user1", method: "reject", contype: "hostnossl"  } ,  {users: "user1", method: "scram-sha-256", contype: hostssl}]





```

##### EXPECTED RESULTS
```

hostnossl all     user1   0.0.0.0/0    reject
hostssl all     user1   0.0.0.0/0       scram-sha-256

```

##### ACTUAL RESULTS

```
hostssl all     user1   0.0.0.0/0       scram-sha-256
```
