### ISSUE TITLE
add huge_pages_status to postgresql_info output

### ISSUE THREAD

**Issue by hunleyd** [ansible-collections/community.postgresql#746]
##### SUMMARY

With the release of PG 17, we should include the value of `huge_pages_status` in the output of postgresql_info to make it easy to determine if huge pages are in use by PG or not

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

postgresql_info

##### ADDITIONAL INFORMATION

```yaml
- name: Collect PostgreSQL version and extensions
  become: true
  become_user: postgres
  community.postgresql.postgresql_info:
  register: 'pginfo'

- ansible.builtin.assert:
    that:
      - pginfo['huge_pages_status']
    fail_msg: 'PG was not able to allocate huge pages'
```
