### ISSUE TITLE
pg15+ show shared_memory_size and sharedmemory_size_in_huge_pages in postgresql_info output

### ISSUE THREAD

**Issue by hunleyd** [ansible-collections/community.postgresql#747]
##### SUMMARY

We should return the `shared_memory_size` and `shared_memory_size_in_huge_pages` (linux) as part of our info. This should probably happen after #746 
##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

postgresql_info
##### ADDITIONAL INFORMATION

```yaml
- name: Collect PostgreSQL version and extensions
  become: true
  become_user: postgres
  community.postgresql.postgresql_info:
  register: 'pginfo'

- ansible.builtin.debug:
    msg: "{{ pginfo['shared_memory_size'] }}"

- asible.builtin.debug:
    msg: "{{ pginfo['shared_memory_size_in_huge_pages'] }}"
      - pginfo['huge_pages_status']
```
