### ISSUE TITLE
report 'in_hot_standby' for pg14+ in postgresql_info

### ISSUE THREAD

**Issue by hunleyd** [ansible-collections/community.postgresql#749]
##### SUMMARY

With the release of PG 14, we should include the value of in_hot_standby in the output of postgresql_info to make it easy to determine if the node is in hot standby mode or not

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

postgresql_info

##### ADDITIONAL INFORMATION

```yaml
- name: Collect PostgreSQL version and extensions
  become: true
  become_user: postgres
  community.postgresql.postgresql_info:
  register: 'pginfo'

- ansible.builtin.assert:
    that:
      - not pginfo['in_hot_standby']
    fail_msg: 'PG is not writeable; is hot standby'
```
