### ISSUE TITLE
community.postgresql.postgresql_pg_hba [3.8.0] Problem "has host bits set"

### ISSUE THREAD

**Issue by anvgarifullin** [ansible-collections/community.postgresql#774]
##### SUMMARY
When working with the configured pg_hba.conf, I get the error ("changed": false, "msg": "Error reading file:\nError in line 88: 127.0.0.1/28 has host bits set"). This happens if the host byte is set, although it is expected to be 0. Before that, we were working with version 3.4.0 and there was no such error. There was no error when installing 3.4.0.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
community.postgresql.postgresql_pg_hba

##### ANSIBLE VERSION
```
ansible --version
ansible [core 2.17.6]
python version = 3.10.12 (main, Nov  6 2024, 20:22:13) [GCC 11.4.0] (/usr/bin/python3)
jinja version = 3.0.3
```

##### OS / ENVIRONMENT
Ubuntu 22.04

##### STEPS TO REPRODUCE
pg_hba.conf contains the ip 127.0.0.1/28:
  host    all     username 127.0.0.1/28    trust

```yaml
- name: Edit pg_hba
  vars:
    ansible_python_interpreter: '/usr/bin/python3'
  community.postgresql.postgresql_pg_hba:
    dest: "{{ hba_path }}"
    address: "{{ hostvars[groups['monitoring_server'][0]]['ansible_default_ipv4']['address'] }}/32"
    backup: true
    contype: host
    databases: "{{ gp_base }}"
    method: md5
    state: present
    users: "{{ gp_user }}"
```

##### EXPECTED RESULTS
It works without error or is there a parameter to disable strict mode as in python.ipaddress.IPv4Network(address, **strict=True**)

##### ACTUAL RESULTS
{"changed": false, "msg": "Error reading file:\nError in line 88: 127.0.0.1/28 has host bits set"}
