### ISSUE TITLE
community.postgresql.postgresql_set incorrectly quotes strings containing commas

### ISSUE THREAD

**Issue by nergdron** [ansible-collections/community.postgresql#78]
just tested the latest release (`1.2.0`) since it was only released 15h ago, devel doesn't have any notable changes i can see which would affect this bug.

##### SUMMARY
when using `postgresql_set` with a string value that contains a comma, for some reason it puts extra doublequotes (`"`) around the string, breaking it when it's included in `postgresql.auto.conf`:

```
password_encryption = 'scram-sha-256'
shared_preload_libraries = '"pg_stat_statements,repmgr"'
```

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
community.postgresql.postgresql_set

##### ANSIBLE VERSION
```paste below
ansible 2.10.6
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/tessa/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/tessa/.local/lib/python3.9/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.9.2 (default, Feb 20 2021, 18:40:11) [GCC 10.2.0]
```

##### CONFIGURATION
```
```

##### OS / ENVIRONMENT
EndeavourOS (Arch variant) running Ansible from system `ansible` package, version 3.1.0.

##### STEPS TO REPRODUCE
in role `defaults/main.yml`:
```yaml
postgres:
  config:
    password_encryption: scram-sha-256
    shared_preload_libraries: pg_stat_statements,repmgr
```

and in role `tasks/main.yml`
```yaml
- name: configure postgresql
  community.postgresql.postgresql_set:
    name: "{{ item.key }}"
    value: "{{ item.value }}"
  become_user: postgres
  loop: "{{ postgres.config | dict2items }}"
  notify: restart postgres
```

##### EXPECTED RESULTS
keys with values that contain commas get correctly rendered out to postgresql and entered into the `postgresql.auto.conf` without extraneous quotes.

##### ACTUAL RESULTS
for some reason module renders values with commas with extra double quotes around them, breaking postgres config. I've verified that if I change the above config line to the following, it works correctly and doesn't inject extra quotes:
```yaml
    shared_preload_libraries: repmgr
```

interestingly, ansible doesn't show the extra quotes in the command output, they only show up in the destination file itself:
```paste below
TASK [postgres : configure postgresql] ********************************************
changed: [mgmt1] => (item={'key': 'password_encryption', 'value': 'scram-sha-256'})
changed: [mgmt1] => (item={'key': 'shared_preload_libraries', 'value': 'pg_stat_statements,repmgr'})
[...]
$ cat /var/lib/postgresql/12/main# cat postgresql.auto.conf
[...]
password_encryption = 'scram-sha-256'
shared_preload_libraries = '"pg_stat_statements,repmgr"'
```
