### ISSUE TITLE
Measure Execution Time with postgresql_query and postgresql_script

### ISSUE THREAD

**Issue by optica-phoffmann** [ansible-collections/community.postgresql#787]
##### SUMMARY
I want to be able to get the execution time of an sql query. I searched the docs of postgresql_query and postgresql_script. I looks like this feature is currently not available. I searched the issues in this repo but couldn't find any discussion about this.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
- postgresql_query
- postgresql_script

##### ADDITIONAL INFORMATION

Ansible Task Example:
```yaml
- name: Simple select query to acme db
  community.postgresql.postgresql_query:
    db: acme
    query: SELECT id FROM accounts
    measure_time: yes
```

Additional Return value
```yaml
execution_time_ms: 7104.652
```
