### ISSUE TITLE
Wrong value limitation on unix_socket_permissions using postgresql_set

### ISSUE THREAD

**Issue by rmaziere** [ansible-collections/community.postgresql#809]
##### SUMMARY

`unix_socket_permissions` limitation using `community.postgresql.postgresql_set`is not compatible with PostgreSQL.

 [PostgreSQL official documentation ](https://www.postgresql.org/docs/17/runtime-config-connection.html) gives : 

> Unix-domain sockets use the usual Unix file system permission set.
> The default permissions are 0777...

And [the source code of PostgreSQL](https://git.postgresql.org/gitweb/?p=postgresql.git&a=search&h=881455e57b1210174b89bb3b13cad6b30b236d50&st=grep&s=unix_socket_permissions)

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

`community.postgresql.postgresql_set`

##### ANSIBLE VERSION

```paste below
core 2.17.8
```

##### COLLECTION VERSION

```paste below
community.postgresql 3.9.0
```

##### CONFIGURATION

```paste below
CONFIG_FILE() = /home/user/.ansible.cfg
DEPRECATION_WARNINGS(/home/user/.ansible.cfg) = False
HOST_KEY_CHECKING(/home/user/.ansible.cfg) = False
```

##### OS / ENVIRONMENT

Ubuntu - Debian

##### STEPS TO REPRODUCE

```yaml
- name: Personalize conf
  community.postgresql.postgresql_set:
    name: "{{ item['name'] }}"
    value: "{{ item['value'] }}"
  with_items: "{{ postgresql.conf }}"
  notify: Restart Postgresql

# With vars
# First example :
postgresql:
  conf:
    - { name: unix_socket_permissions, value: 0770 }

# Second example :
postgresql:
  conf:
    - { name: unix_socket_permissions, value: 770 }
```

##### EXPECTED RESULTS

```paste below
TASK [postgresql : Personalize conf] ***************************************************************************
changed: [postgresql] => (item={'name': 'unix_socket_permissions', 'value': 0770})
```

##### ACTUAL RESULTS

```paste below
# First example :
TASK [postgresql : Personalize conf] ***************************************************************************
changed: [postgresql] => (item={'name': 'unix_socket_permissions', 'value': 504})

# Second example :
TASK [postgresql : Personalize conf] ***************************************************************************
failed: [postgresql] (item={'name': 'unix_socket_permissions', 'value': 770}) => {"ansible_loop_var": "item", "changed": false, "item": {"name": "unix_socket_permissions", "value": 770}, "msg": "Unable to set unix_socket_permissions value due to : ERREUR:  770 is outside the valid range for parameter \"unix_socket_permissions\" (0 .. 511)\n"}
```
