### ISSUE TITLE
Documentation missing certificate use examples

### ISSUE THREAD

**Issue by v2x2799** [ansible-collections/community.postgresql#811]
##### SUMMARY

Existing documentation does not provide any examples of how to connect to a database using a certificate/PEM file.  
 For example, AWS RDS database connections require use of an Amazon certificate/PEM file.  The PEM file is registered in the execution environment's cert store, but the exact syntax on how to use/reference the PEM is not clearly defined in any of the connection examples.  

##### ISSUE TYPE
- Documentation Report

##### COMPONENT NAME

Module: postgresql_query  Commands: ssl_cert, ca_cert
##### ANSIBLE VERSION

```paste below
ansible [core 2.15.13]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.9/site-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.9.20 (main, Sep 26 2024, 20:59:47) [GCC 8.5.0 20210514 (Red Hat 8.5.0-22)] (/usr/bin/python3.9)
  jinja version = 3.1.5
  libyaml = True

```

**Comment by betanummeric** [comment]
@v2x2799 [standard evironment variables](https://www.postgresql.org/docs/current/libpq-envars.html) should work, something like this:
```yaml
- name: example query
  community.postgresql.postgresql_query:
    db: example_db
    query: SELECT version()
  environment:
    PGSSLCERT: ~/.postgresql/postgresql.crt
    PGSSLKEY: ~/.postgresql/postgresql.key
    PGSSLMODE: verify-full
    PGSSLROOTCERT: ~/.postgresql/root.crt
```
