### ISSUE TITLE
Add Features for renaming users in the postgresql_user module

### ISSUE THREAD

**Issue by azdfzshffg** [ansible-collections/community.postgresql#815]
SUMMARY
Currently, the _community.postgresql.postgresql_user_ module does not support renaming a user. This feature would allow renaming a PostgreSQL user directly within the module instead of requiring a separate SQL query.

ISSUE TYPE
Feature Idea
COMPONENT NAME
community.postgresql.postgresql_user

ADDITIONAL INFORMATION
This feature would simplify user management by allowing a direct rename operation without needing to execute a raw SQL query (ALTER ROLE old_name RENAME TO new_name;).
It would be useful for maintaining consistency in PostgreSQL role management, especially in automated deployments.

Example of expected usage:

```
- name: Rename PostgreSQL user
  community.postgresql.postgresql_user:
    name: "old_user"
    new_name: "new_user"
    login_db: "postgres"
    login_user: "admin"
    login_password: "admin_password"
    login_port: 5432
```

This would improve usability and reduce the need for raw SQL queries in playbooks.😊

Thanks
