### ISSUE TITLE
add support to restore from directory formats

### ISSUE THREAD

**Issue by landryb** [ansible-collections/community.postgresql#83]
##### SUMMARY
`db_restore` has support for pgc and tar formats, would be nice to have directory (which is compressed by default)

for some reasons (being able to pass arbitrary `pg_restore` options) i'm not comfortable with using dumps restored with psql, supported via .sql.gz, .sql.xz, etc..

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
postgresql_db

##### ADDITIONAL INFORMATION

```yaml
postgresql_db:
  name: mydb
  target: /tmp/dump/
  state: restore
```

would under the hood use `--format=directory`
