### ISSUE TITLE
community.postgresql.postgresql_db - `session_role` not respected when `state` is dump/restore

### ISSUE THREAD

**Issue by gspanos** [ansible-collections/community.postgresql#864]
##### SUMMARY
`session_role` parameter is ignored when `state` has the value "dump" or "restore". This leads to `pg_restore` assigning ownership of the created objects to the `login_user`. 

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
community.postgresql.postgresql_db

##### ANSIBLE VERSION

```paste below
ansible [core 2.18.1]
  config file = None
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.12/site-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.12.10 (main, May 21 2025, 20:03:03) [GCC 14.2.0] (/usr/bin/python3)
  jinja version = 3.1.6
  libyaml = True
```

##### COLLECTION VERSION

```paste below
# /usr/lib/python3.12/site-packages/ansible_collections
Collection           Version
-------------------- -------
community.postgresql 3.9.0
```

##### CONFIGURATION

```paste below
CONFIG_FILE() = None
DEFAULT_ROLES_PATH(env: ANSIBLE_ROLES_PATH) = ['/app/ansible/roles']

GALAXY_SERVERS:
```

##### OS / ENVIRONMENT

Ubuntu 22.04.5 LTS which runs the ansible playbook on alpine:3.21 via docker 

##### STEPS TO REPRODUCE

```yaml
- name: restore some archive
  community.postgresql.postgresql_db:
    login_host: "{{ login_host }}"
    login_user: "{{ login_user }}"
    login_password: "{{ postgres_passwd }}"
    session_role: myrole
    name: mydb
    state: restore
    target: /tmp/backup.sql
```

##### EXPECTED RESULTS

I expect the database objects being restored to be owned by the `session_role`

##### ACTUAL RESULTS

The objects restored are instead owned by the `login_user` 

```paste below

```
